"""
CDM Catalog Definitions - ACH Extension Table
US Automated Clearing House payment-specific fields
"""

CDM_EXTENSION_ACH = {
    'cdm_payment_extension_ach': {
        'extension_id': {
            'business_name': 'Extension ID',
            'business_description': 'Unique identifier for this ACH extension record.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'instruction_id': {
            'business_name': 'Instruction ID',
            'business_description': 'Foreign key to the parent payment instruction.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'immediate_destination': {
            'business_name': 'Immediate Destination',
            'business_description': 'Per NACHA: ABA routing number of the ACH Operator or receiving point where the file is sent. Position 4-13 of File Header.',
            'data_format': '9-digit ABA routing number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'immediate_origin': {
            'business_name': 'Immediate Origin',
            'business_description': 'Per NACHA: ABA routing number of the ODFI (Originating Depository Financial Institution). Identifies the sender of the file.',
            'data_format': '9-digit ABA routing number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'immediate_destination_name': {
            'business_name': 'Immediate Destination Name',
            'business_description': 'Per NACHA: Name of the ACH Operator or RDFI receiving the file.',
            'data_format': 'Text, max 23 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'immediate_origin_name': {
            'business_name': 'Immediate Origin Name',
            'business_description': 'Per NACHA: Name of the ODFI originating the file.',
            'data_format': 'Text, max 23 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_creation_date': {
            'business_name': 'File Creation Date',
            'business_description': 'Per NACHA: Date the file was created. Format YYMMDD.',
            'data_format': 'YYMMDD',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_creation_time': {
            'business_name': 'File Creation Time',
            'business_description': 'Per NACHA: Time the file was created. Format HHMM.',
            'data_format': 'HHMM (24-hour)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_id_modifier': {
            'business_name': 'File ID Modifier',
            'business_description': 'Per NACHA: Code to distinguish between multiple files created on the same date (A-Z, 0-9). Allows up to 36 files per day.',
            'data_format': 'Single alphanumeric character',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'standard_entry_class': {
            'business_name': 'Standard Entry Class (SEC) Code',
            'business_description': 'Per NACHA: Three-character code identifying the type of ACH entry. Common codes: PPD (Prearranged Payment/Deposit), CCD (Corporate Credit/Debit), CTX (Corporate Trade Exchange), WEB (Internet-Initiated), TEL (Telephone-Initiated).',
            'data_format': '3-character code',
            'allowed_values': [
                {'value': 'PPD', 'description': 'Prearranged Payment and Deposit - Consumer'},
                {'value': 'CCD', 'description': 'Corporate Credit or Debit'},
                {'value': 'CTX', 'description': 'Corporate Trade Exchange'},
                {'value': 'WEB', 'description': 'Internet-Initiated Entry'},
                {'value': 'TEL', 'description': 'Telephone-Initiated Entry'},
                {'value': 'ARC', 'description': 'Accounts Receivable Entry'},
                {'value': 'BOC', 'description': 'Back Office Conversion'},
                {'value': 'POP', 'description': 'Point-of-Purchase Entry'},
                {'value': 'RCK', 'description': 'Re-presented Check Entry'},
                {'value': 'IAT', 'description': 'International ACH Transaction'},
            ],
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'company_name': {
            'business_name': 'Company Name',
            'business_description': 'Per NACHA: Name of the company originating the ACH entries. Appears on receiver statement.',
            'data_format': 'Text, max 16 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'company_identification': {
            'business_name': 'Company Identification',
            'business_description': 'Per NACHA: Identification number of the originating company. Typically EIN (Employer Identification Number) with 1 prefix.',
            'data_format': '10 characters (1+9 digit EIN)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'company_entry_description': {
            'business_name': 'Company Entry Description',
            'business_description': 'Per NACHA: Description of the transaction type that appears on receiver statement. Examples: PAYROLL, PAYMENT, DIRECT PAY.',
            'data_format': 'Text, max 10 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'effective_entry_date': {
            'business_name': 'Effective Entry Date',
            'business_description': 'Per NACHA: Date on which the originator intends the entries to be settled. RDFI may post entries on this date.',
            'data_format': 'YYMMDD',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'settlement_date': {
            'business_name': 'Settlement Date',
            'business_description': 'Per NACHA: Date on which the ACH Operator settles the transaction. Inserted by ACH Operator.',
            'data_format': 'Julian date (0YYddd)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'batch_number': {
            'business_name': 'Batch Number',
            'business_description': 'Per NACHA: Sequential number identifying the batch within the file. Starts at 1 for each file.',
            'data_format': '7-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'originator_status_code': {
            'business_name': 'Originator Status Code',
            'business_description': 'Per NACHA: Code identifying the type of entity originating the transaction. 1=Bank/FI, 0=Non-FI.',
            'data_format': 'Single digit',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'transaction_code': {
            'business_name': 'Transaction Code',
            'business_description': 'Per NACHA: Two-digit code indicating the type of transaction. First digit: 2=checking, 3=savings. Second digit: 2=credit, 7=debit.',
            'data_format': '2-digit code',
            'allowed_values': [
                {'value': '22', 'description': 'Checking Credit (Deposit)'},
                {'value': '23', 'description': 'Checking Credit Prenote'},
                {'value': '27', 'description': 'Checking Debit (Withdrawal)'},
                {'value': '28', 'description': 'Checking Debit Prenote'},
                {'value': '32', 'description': 'Savings Credit (Deposit)'},
                {'value': '33', 'description': 'Savings Credit Prenote'},
                {'value': '37', 'description': 'Savings Debit (Withdrawal)'},
                {'value': '38', 'description': 'Savings Debit Prenote'},
            ],
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'originating_dfi_id': {
            'business_name': 'Originating DFI ID',
            'business_description': 'Per NACHA: ABA routing number (first 8 digits) of the ODFI originating the entry.',
            'data_format': '8-digit ABA transit routing number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'receiving_dfi_id': {
            'business_name': 'Receiving DFI ID',
            'business_description': 'Per NACHA: ABA routing number (first 8 digits) of the RDFI where the receiver account is held.',
            'data_format': '8-digit ABA transit routing number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'individual_id': {
            'business_name': 'Individual Identification Number',
            'business_description': 'Per NACHA: Identification number of the receiver. Format varies by SEC code (SSN, account number, etc.).',
            'data_format': 'Text, max 15 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'individual_name': {
            'business_name': 'Individual Name',
            'business_description': 'Per NACHA: Name of the receiver (individual or company) for the ACH entry.',
            'data_format': 'Text, max 22 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'trace_number': {
            'business_name': 'Trace Number',
            'business_description': 'Per NACHA: Unique 15-digit number assigned by ODFI to identify each entry. First 8 digits are ODFI routing number.',
            'data_format': '15-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'discretionary_data': {
            'business_name': 'Discretionary Data',
            'business_description': 'Per NACHA: Optional field for use by ODFI and originator. Meaning varies by agreement.',
            'data_format': 'Text, max 2 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'addenda_indicator': {
            'business_name': 'Addenda Record Indicator',
            'business_description': 'Per NACHA: Indicates whether addenda records follow this entry. 0=No addenda, 1=Addenda follows.',
            'data_format': 'Single digit (0 or 1)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'addenda_type': {
            'business_name': 'Addenda Type Code',
            'business_description': 'Per NACHA: Code identifying the type of addenda record. 05=Payment-related info, 98=Change notification, 99=Return.',
            'data_format': '2-digit code',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'addenda_info': {
            'business_name': 'Addenda Information',
            'business_description': 'Per NACHA: Payment-related information in the addenda record. Content varies by addenda type.',
            'data_format': 'Text, max 80 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'return_reason_code': {
            'business_name': 'Return Reason Code',
            'business_description': 'Per NACHA: Three-character code indicating why an entry was returned. Examples: R01=Insufficient Funds, R02=Account Closed, R03=No Account.',
            'data_format': '3-character code',
            'allowed_values': [
                {'value': 'R01', 'description': 'Insufficient Funds'},
                {'value': 'R02', 'description': 'Account Closed'},
                {'value': 'R03', 'description': 'No Account/Unable to Locate'},
                {'value': 'R04', 'description': 'Invalid Account Number'},
                {'value': 'R05', 'description': 'Unauthorized Debit'},
                {'value': 'R06', 'description': 'Returned per ODFI Request'},
                {'value': 'R07', 'description': 'Authorization Revoked'},
                {'value': 'R08', 'description': 'Payment Stopped'},
                {'value': 'R09', 'description': 'Uncollected Funds'},
                {'value': 'R10', 'description': 'Customer Advises Not Authorized'},
            ],
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_entry_trace': {
            'business_name': 'Original Entry Trace Number',
            'business_description': 'Per NACHA: Trace number of the original entry being returned or corrected.',
            'data_format': '15-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_receiving_dfi': {
            'business_name': 'Original Receiving DFI',
            'business_description': 'Per NACHA: Routing number of the RDFI from the original entry.',
            'data_format': '8-digit ABA routing number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'date_of_death': {
            'business_name': 'Date of Death',
            'business_description': 'Per NACHA: For return code R14/R15, the date of death of the account holder.',
            'data_format': 'YYMMDD',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'created_at': {
            'business_name': 'Created At',
            'business_description': 'Timestamp when this ACH extension record was created.',
            'data_format': 'ISO 8601 DateTime',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'raw_id': {
            'business_name': 'Raw ID',
            'business_description': 'Reference to the Bronze layer raw record.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # Record Type Indicators
        # ============================================================
        'file_header_record_type': {
            'business_name': 'File Header Record Type',
            'business_description': 'Per NACHA: Record type code for file header (always "1"). Position 1 of File Header Record.',
            'data_format': 'Single digit (1)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'batch_header_record_type': {
            'business_name': 'Batch Header Record Type',
            'business_description': 'Per NACHA: Record type code for batch header (always "5"). Position 1 of Batch Header Record.',
            'data_format': 'Single digit (5)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'entry_detail_record_type': {
            'business_name': 'Entry Detail Record Type',
            'business_description': 'Per NACHA: Record type code for entry detail (always "6"). Position 1 of Entry Detail Record.',
            'data_format': 'Single digit (6)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'addenda_record_type': {
            'business_name': 'Addenda Record Type',
            'business_description': 'Per NACHA: Record type code for addenda record (always "7"). Position 1 of Addenda Record.',
            'data_format': 'Single digit (7)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'batch_ctrl_record_type': {
            'business_name': 'Batch Control Record Type',
            'business_description': 'Per NACHA: Record type code for batch control (always "8"). Position 1 of Batch Control Record.',
            'data_format': 'Single digit (8)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_ctrl_record_type': {
            'business_name': 'File Control Record Type',
            'business_description': 'Per NACHA: Record type code for file control (always "9"). Position 1 of File Control Record.',
            'data_format': 'Single digit (9)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # File Header Fields
        # ============================================================
        'priority_code': {
            'business_name': 'Priority Code',
            'business_description': 'Per NACHA: Processing priority code (always "01"). Position 2-3 of File Header Record.',
            'data_format': '2-digit code (01)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'record_size': {
            'business_name': 'Record Size',
            'business_description': 'Per NACHA: Fixed length of each record (always "094"). Position 35-37 of File Header Record.',
            'data_format': '3-digit number (094)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'blocking_factor': {
            'business_name': 'Blocking Factor',
            'business_description': 'Per NACHA: Number of records per block (always "10"). Position 38-39 of File Header Record.',
            'data_format': '2-digit number (10)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'format_code': {
            'business_name': 'Format Code',
            'business_description': 'Per NACHA: Format code indicator (always "1"). Position 40 of File Header Record.',
            'data_format': 'Single digit (1)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'reference_code': {
            'business_name': 'Reference Code',
            'business_description': 'Per NACHA: Optional reference code for the file. Position 88-94 of File Header Record. For use by originator.',
            'data_format': 'Text, 8 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # Batch Header Fields
        # ============================================================
        'service_class_code': {
            'business_name': 'Service Class Code',
            'business_description': 'Per NACHA: Code identifying the type of entries in the batch. 200=Mixed debits and credits, 220=Credits only, 225=Debits only.',
            'data_format': '3-digit code',
            'allowed_values': [
                {'value': '200', 'description': 'Mixed Debits and Credits'},
                {'value': '220', 'description': 'Credits Only'},
                {'value': '225', 'description': 'Debits Only'},
            ],
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'company_discretionary_data': {
            'business_name': 'Company Discretionary Data',
            'business_description': 'Per NACHA: Optional field for use by originator. 20 characters available for internal use.',
            'data_format': 'Text, max 20 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'company_descriptive_date': {
            'business_name': 'Company Descriptive Date',
            'business_description': 'Per NACHA: Optional date field that appears on receiver statement. Can be any descriptive date chosen by originator.',
            'data_format': 'Text, 6 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'message_authentication_code': {
            'business_name': 'Message Authentication Code',
            'business_description': 'Per NACHA: Optional security validation code computed using encryption. Reserved for future use.',
            'data_format': 'Text, 19 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # Entry Detail Fields
        # ============================================================
        'check_digit': {
            'business_name': 'Check Digit',
            'business_description': 'Per NACHA: The 9th digit of the receiving DFI routing number. Used to validate the routing number.',
            'data_format': 'Single digit',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'entry_detail_sequence_number': {
            'business_name': 'Entry Detail Sequence Number',
            'business_description': 'Per NACHA: Last 7 digits of the trace number. Sequential number assigned by ODFI to each entry within a batch.',
            'data_format': '7-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # Addenda Fields
        # ============================================================
        'addenda_sequence_number': {
            'business_name': 'Addenda Sequence Number',
            'business_description': 'Per NACHA: Sequential number of this addenda record within the entry. Starts at 1 for each entry.',
            'data_format': '4-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'change_code': {
            'business_name': 'Change Code (NOC)',
            'business_description': 'Per NACHA: Notification of Change code indicating what data element needs correction. Examples: C01=Account Number, C02=Routing Number.',
            'data_format': '3-character code',
            'allowed_values': [
                {'value': 'C01', 'description': 'Incorrect DFI Account Number'},
                {'value': 'C02', 'description': 'Incorrect Routing Number'},
                {'value': 'C03', 'description': 'Incorrect Routing Number and Account Number'},
                {'value': 'C04', 'description': 'Incorrect Individual Name'},
                {'value': 'C05', 'description': 'Incorrect Transaction Code'},
                {'value': 'C06', 'description': 'Incorrect Account Number and Transaction Code'},
                {'value': 'C07', 'description': 'Incorrect Routing Number, Account Number, and TC'},
            ],
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'corrected_data': {
            'business_name': 'Corrected Data (NOC)',
            'business_description': 'Per NACHA: The correct data to replace erroneous data in the original entry. Format depends on change code.',
            'data_format': 'Text, max 29 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_entry_trace_number_noc': {
            'business_name': 'Original Entry Trace Number (NOC)',
            'business_description': 'Per NACHA: Trace number from the original entry requiring correction. Used in Notification of Change.',
            'data_format': '15-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # Batch Control Fields
        # ============================================================
        'batch_ctrl_service_class_code': {
            'business_name': 'Batch Control Service Class Code',
            'business_description': 'Per NACHA: Service class code in batch control. Must match batch header.',
            'data_format': '3-digit code',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'entry_addenda_count': {
            'business_name': 'Entry/Addenda Count',
            'business_description': 'Per NACHA: Total count of entry detail and addenda records in the batch.',
            'data_format': '6-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'entry_hash': {
            'business_name': 'Entry Hash',
            'business_description': 'Per NACHA: Sum of all receiving DFI routing numbers (first 8 digits) in the batch. Used for validation.',
            'data_format': '10-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'total_debit_amount': {
            'business_name': 'Total Debit Entry Dollar Amount',
            'business_description': 'Per NACHA: Sum of all debit amounts in the batch. In cents (implied 2 decimal places).',
            'data_format': '12-digit number (in cents)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'total_credit_amount': {
            'business_name': 'Total Credit Entry Dollar Amount',
            'business_description': 'Per NACHA: Sum of all credit amounts in the batch. In cents (implied 2 decimal places).',
            'data_format': '12-digit number (in cents)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'batch_ctrl_company_id': {
            'business_name': 'Batch Control Company ID',
            'business_description': 'Per NACHA: Company identification in batch control. Must match batch header.',
            'data_format': '10 characters',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'batch_ctrl_originating_dfi': {
            'business_name': 'Batch Control Originating DFI',
            'business_description': 'Per NACHA: Originating DFI ID in batch control. Must match batch header.',
            'data_format': '8-digit ABA routing number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'batch_ctrl_batch_number': {
            'business_name': 'Batch Control Batch Number',
            'business_description': 'Per NACHA: Batch number in batch control. Must match batch header.',
            'data_format': '7-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'batch_ctrl_reserved': {
            'business_name': 'Batch Control Reserved',
            'business_description': 'Per NACHA: Reserved field in batch control record. Left blank (spaces).',
            'data_format': 'Text, 6 spaces',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # File Control Fields
        # ============================================================
        'file_ctrl_batch_count': {
            'business_name': 'File Control Batch Count',
            'business_description': 'Per NACHA: Total number of batches in the file.',
            'data_format': '6-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_ctrl_block_count': {
            'business_name': 'File Control Block Count',
            'business_description': 'Per NACHA: Total number of physical blocks in the file. Calculated as total records divided by blocking factor (10).',
            'data_format': '6-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_ctrl_entry_addenda_count': {
            'business_name': 'File Control Entry/Addenda Count',
            'business_description': 'Per NACHA: Total count of entry detail and addenda records in the entire file.',
            'data_format': '8-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_ctrl_entry_hash': {
            'business_name': 'File Control Entry Hash',
            'business_description': 'Per NACHA: Sum of all entry hashes from all batches. Used for file-level validation.',
            'data_format': '10-digit number',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_ctrl_total_debit_amount': {
            'business_name': 'File Control Total Debit Amount',
            'business_description': 'Per NACHA: Sum of all debit amounts from all batches in the file. In cents.',
            'data_format': '12-digit number (in cents)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_ctrl_total_credit_amount': {
            'business_name': 'File Control Total Credit Amount',
            'business_description': 'Per NACHA: Sum of all credit amounts from all batches in the file. In cents.',
            'data_format': '12-digit number (in cents)',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'file_ctrl_reserved': {
            'business_name': 'File Control Reserved',
            'business_description': 'Per NACHA: Reserved field in file control record. Left blank (spaces).',
            'data_format': 'Text, 39 spaces',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        # ============================================================
        # SEC Code Flags (Boolean indicators for entry type)
        # ============================================================
        'sec_arc': {
            'business_name': 'SEC Code: ARC',
            'business_description': 'Per NACHA: Accounts Receivable Entry. Consumer check converted to ACH debit at lockbox or merchant location.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_boc': {
            'business_name': 'SEC Code: BOC',
            'business_description': 'Per NACHA: Back Office Conversion. Check converted at point of purchase after customer leaves.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_ccd': {
            'business_name': 'SEC Code: CCD',
            'business_description': 'Per NACHA: Corporate Credit or Debit. B2B payment with or without addenda for cash concentration/disbursement.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_ctx': {
            'business_name': 'SEC Code: CTX',
            'business_description': 'Per NACHA: Corporate Trade Exchange. B2B payment with ANSI X12 or UN/EDIFACT addenda for EDI transactions.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_enr': {
            'business_name': 'SEC Code: ENR',
            'business_description': 'Per NACHA: Automated Enrollment Entry. Used by federal government to enroll recipients in benefits programs.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_iat': {
            'business_name': 'SEC Code: IAT',
            'business_description': 'Per NACHA: International ACH Transaction. Cross-border payment requiring OFAC screening and additional addenda.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_mte': {
            'business_name': 'SEC Code: MTE',
            'business_description': 'Per NACHA: Machine Transfer Entry. ATM-initiated transaction where terminal operator transfers funds.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_pop': {
            'business_name': 'SEC Code: POP',
            'business_description': 'Per NACHA: Point-of-Purchase Entry. Check converted at point of sale in presence of customer.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_pos': {
            'business_name': 'SEC Code: POS',
            'business_description': 'Per NACHA: Point-of-Sale Entry. Debit card or PIN-authenticated transaction at point of sale.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_ppd': {
            'business_name': 'SEC Code: PPD',
            'business_description': 'Per NACHA: Prearranged Payment and Deposit. Consumer payment with written authorization (direct deposit, autopay).',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_rck': {
            'business_name': 'SEC Code: RCK',
            'business_description': 'Per NACHA: Re-presented Check Entry. Returned check re-presented electronically as ACH debit.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_shr': {
            'business_name': 'SEC Code: SHR',
            'business_description': 'Per NACHA: Shared Network Transaction. Debit card transaction through shared ATM network.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_tel': {
            'business_name': 'SEC Code: TEL',
            'business_description': 'Per NACHA: Telephone-Initiated Entry. Single payment authorized via telephone call.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_trc': {
            'business_name': 'SEC Code: TRC',
            'business_description': 'Per NACHA: Truncated Entry. Check truncated and cleared electronically. Legacy code, rarely used.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_web': {
            'business_name': 'SEC Code: WEB',
            'business_description': 'Per NACHA: Internet-Initiated Entry. Payment authorized via internet or mobile banking.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'sec_xck': {
            'business_name': 'SEC Code: XCK',
            'business_description': 'Per NACHA: Destroyed Check Entry. Replacement for check that was lost or destroyed.',
            'data_format': 'Boolean',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
    },
}
