"""
CDM Catalog Definitions - ISO 20022 pacs (Payments Clearing and Settlement) Tables
Includes pacs.008, pacs.002, pacs.004, pacs.009
"""

# Common field definitions reused across pacs tables
_COMMON_PACS_FIELDS = {
    'instruction_id': {
        'business_name': 'Instruction ID',
        'business_description': 'Unique identifier for this payment instruction in the CDM.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'message_id': {
        'business_name': 'Message Identification',
        'business_description': 'Per ISO 20022: Point-to-point reference assigned by the instructing party to identify the message.',
        'iso_element_name': 'MessageIdentification',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/GrpHdr/MsgId | Document/FICdtTrf/GrpHdr/MsgId | Document/FIToFIPmtStsRpt/GrpHdr/MsgId | Document/PmtRtr/GrpHdr/MsgId',
        'iso_data_type': 'Max35Text',
    },
    'creation_datetime': {
        'business_name': 'Creation Date Time',
        'business_description': 'Per ISO 20022: Date and time at which the message was created.',
        'iso_element_name': 'CreationDateTime',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/GrpHdr/CreDtTm | Document/FICdtTrf/GrpHdr/CreDtTm | Document/FIToFIPmtStsRpt/GrpHdr/CreDtTm | Document/PmtRtr/GrpHdr/CreDtTm',
        'iso_data_type': 'ISODateTime',
    },
    'number_of_transactions': {
        'business_name': 'Number of Transactions',
        'business_description': 'Per ISO 20022: Number of individual transactions contained in the message.',
        'iso_element_name': 'NumberOfTransactions',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/GrpHdr/NbOfTxs | Document/FICdtTrf/GrpHdr/NbOfTxs | Document/FIToFIPmtStsRpt/GrpHdr/NbOfTxs | Document/PmtRtr/GrpHdr/NbOfTxs',
        'iso_data_type': 'Max15NumericText',
    },
    'settlement_method': {
        'business_name': 'Settlement Method',
        'business_description': 'Per ISO 20022: Method used to settle the credit transfer instruction. INDA=Instructed Agent, INGA=Instructing Agent, COVE=Cover, CLRG=Clearing System.',
        'iso_element_name': 'SettlementMethod',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/GrpHdr/SttlmInf/SttlmMtd | Document/FICdtTrf/GrpHdr/SttlmInf/SttlmMtd | Document/PmtRtr/GrpHdr/SttlmInf/SttlmMtd',
        'iso_data_type': 'SettlementMethod1Code',
    },
    'interbank_settlement_date': {
        'business_name': 'Interbank Settlement Date',
        'business_description': 'Per ISO 20022: Date on which the amount of money ceases to be available to the agent that owes it and when the amount becomes available to the agent to which it is due.',
        'iso_element_name': 'InterbankSettlementDate',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/IntrBkSttlmDt | Document/FICdtTrf/CdtTrfTxInf/IntrBkSttlmDt | Document/PmtRtr/TxInf/OrgnlIntrBkSttlmDt',
        'iso_data_type': 'ISODate',
    },
    'interbank_settlement_amount': {
        'business_name': 'Interbank Settlement Amount',
        'business_description': 'Per ISO 20022: Amount of money to be moved between the instructing agent and the instructed agent.',
        'iso_element_name': 'InterbankSettlementAmount',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/IntrBkSttlmAmt | Document/FICdtTrf/CdtTrfTxInf/IntrBkSttlmAmt | Document/PmtRtr/TxInf/RtrdIntrBkSttlmAmt',
        'iso_data_type': 'ActiveCurrencyAndAmount',
    },
    'interbank_settlement_currency': {
        'business_name': 'Interbank Settlement Currency',
        'business_description': 'Per ISO 20022: Currency of the interbank settlement amount.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/IntrBkSttlmAmt/@Ccy | Document/FICdtTrf/CdtTrfTxInf/IntrBkSttlmAmt/@Ccy',
        'iso_data_type': 'ActiveCurrencyCode',
    },
    'instructed_amount': {
        'business_name': 'Instructed Amount',
        'business_description': 'Per ISO 20022: Amount of money to be transferred as instructed by the debtor.',
        'iso_element_name': 'InstructedAmount',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/InstdAmt | Document/FICdtTrf/CdtTrfTxInf/InstdAmt',
        'iso_data_type': 'ActiveOrHistoricCurrencyAndAmount',
    },
    'instructed_currency': {
        'business_name': 'Instructed Currency',
        'business_description': 'Per ISO 20022: Currency of the instructed amount.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/InstdAmt/@Ccy | Document/FICdtTrf/CdtTrfTxInf/InstdAmt/@Ccy',
        'iso_data_type': 'ActiveOrHistoricCurrencyCode',
    },
    'charge_bearer': {
        'business_name': 'Charge Bearer',
        'business_description': 'Per ISO 20022: Specifies which party/parties will bear the charges. DEBT=Debtor, CRED=Creditor, SHAR=Shared, SLEV=Service Level.',
        'iso_element_name': 'ChargeBearer',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/ChrgBr | Document/FICdtTrf/CdtTrfTxInf/ChrgBr',
        'iso_data_type': 'ChargeBearerType1Code',
    },
    'end_to_end_id': {
        'business_name': 'End to End Identification',
        'business_description': 'Per ISO 20022: Unique identification assigned by the initiating party to unambiguously identify the transaction. Passed unchanged throughout the payment chain.',
        'iso_element_name': 'EndToEndIdentification',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/EndToEndId | Document/FICdtTrf/CdtTrfTxInf/PmtId/EndToEndId | Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlEndToEndId | Document/PmtRtr/TxInf/OrgnlEndToEndId',
        'iso_data_type': 'Max35Text',
    },
    'transaction_id': {
        'business_name': 'Transaction Identification',
        'business_description': 'Per ISO 20022: Unique identification assigned by the first instructing agent to identify the transaction.',
        'iso_element_name': 'TransactionIdentification',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/TxId | Document/FICdtTrf/CdtTrfTxInf/PmtId/TxId | Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxId | Document/PmtRtr/TxInf/OrgnlTxId',
        'iso_data_type': 'Max35Text',
    },
    'instruction_identification': {
        'business_name': 'Instruction Identification',
        'business_description': 'Per ISO 20022: Unique identification assigned by an instructing party for an instructed party to identify the instruction.',
        'iso_element_name': 'InstructionIdentification',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/InstrId | Document/FICdtTrf/CdtTrfTxInf/PmtId/InstrId | Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlInstrId',
        'iso_data_type': 'Max35Text',
    },
    'uetr': {
        'business_name': 'UETR',
        'business_description': 'Per ISO 20022: Unique End-to-end Transaction Reference. Globally unique identifier (UUID) for tracking payments across systems.',
        'iso_element_name': 'UETR',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/UETR | Document/FICdtTrf/CdtTrfTxInf/PmtId/UETR | Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlUETR | Document/PmtRtr/TxInf/OrgnlUETR',
        'iso_data_type': 'UUIDv4Identifier',
    },
    'clearing_system_reference': {
        'business_name': 'Clearing System Reference',
        'business_description': 'Per ISO 20022: Unique reference assigned by the clearing system to identify the instruction.',
        'iso_element_name': 'ClearingSystemReference',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtId/ClrSysRef | Document/FICdtTrf/CdtTrfTxInf/PmtId/ClrSysRef | Document/FIToFIPmtStsRpt/TxInfAndSts/ClrSysRef',
        'iso_data_type': 'Max35Text',
    },
    'clearing_system_code': {
        'business_name': 'Clearing System Code',
        'business_description': 'Per ISO 20022: Code identifying the clearing system. Examples: CHAPS, TARGET2, FEDWIRE.',
        'iso_element_name': 'Code',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/GrpHdr/SttlmInf/ClrSys/Cd | Document/FICdtTrf/GrpHdr/SttlmInf/ClrSys/Cd',
        'iso_data_type': 'ExternalClearingSystemIdentification1Code',
    },
    'clearing_system_proprietary': {
        'business_name': 'Clearing System Proprietary',
        'business_description': 'Per ISO 20022: Proprietary identification of the clearing system when no standard code applies.',
        'iso_element_name': 'Proprietary',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/GrpHdr/SttlmInf/ClrSys/Prtry | Document/FICdtTrf/GrpHdr/SttlmInf/ClrSys/Prtry',
        'iso_data_type': 'Max35Text',
    },
    'service_level_code': {
        'business_name': 'Service Level Code',
        'business_description': 'Per ISO 20022: Agreement under which the transaction should be processed. SEPA, URGP (Urgent), NURG (Non-Urgent), etc.',
        'iso_element_name': 'Code',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtTpInf/SvcLvl/Cd | Document/FICdtTrf/CdtTrfTxInf/PmtTpInf/SvcLvl/Cd',
        'iso_data_type': 'ExternalServiceLevel1Code',
    },
    'service_level_proprietary': {
        'business_name': 'Service Level Proprietary',
        'business_description': 'Per ISO 20022: Proprietary service level when no standard code applies.',
        'iso_element_name': 'Proprietary',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtTpInf/SvcLvl/Prtry | Document/FICdtTrf/CdtTrfTxInf/PmtTpInf/SvcLvl/Prtry',
        'iso_data_type': 'Max35Text',
    },
    'local_instrument_code': {
        'business_name': 'Local Instrument Code',
        'business_description': 'Per ISO 20022: User community specific instrument. Specifies the local instrument for the payment.',
        'iso_element_name': 'Code',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtTpInf/LclInstrm/Cd | Document/FICdtTrf/CdtTrfTxInf/PmtTpInf/LclInstrm/Cd',
        'iso_data_type': 'ExternalLocalInstrument1Code',
    },
    'local_instrument_proprietary': {
        'business_name': 'Local Instrument Proprietary',
        'business_description': 'Per ISO 20022: Proprietary local instrument identification.',
        'iso_element_name': 'Proprietary',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtTpInf/LclInstrm/Prtry | Document/FICdtTrf/CdtTrfTxInf/PmtTpInf/LclInstrm/Prtry',
        'iso_data_type': 'Max35Text',
    },
    'category_purpose_code': {
        'business_name': 'Category Purpose Code',
        'business_description': 'Per ISO 20022: High-level purpose of the instruction. CASH, CORT (Trade), DIVI (Dividend), INTC (Intracompany), SALA (Salary), etc.',
        'iso_element_name': 'Code',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtTpInf/CtgyPurp/Cd | Document/FICdtTrf/CdtTrfTxInf/PmtTpInf/CtgyPurp/Cd',
        'iso_data_type': 'ExternalCategoryPurpose1Code',
    },
    'category_purpose_proprietary': {
        'business_name': 'Category Purpose Proprietary',
        'business_description': 'Per ISO 20022: Proprietary category purpose when no standard code applies.',
        'iso_element_name': 'Proprietary',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtTpInf/CtgyPurp/Prtry | Document/FICdtTrf/CdtTrfTxInf/PmtTpInf/CtgyPurp/Prtry',
        'iso_data_type': 'Max35Text',
    },
    'instruction_priority': {
        'business_name': 'Instruction Priority',
        'business_description': 'Per ISO 20022: Indicator of the urgency of the instruction. HIGH or NORM.',
        'iso_element_name': 'InstructionPriority',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/PmtTpInf/InstrPrty | Document/FICdtTrf/CdtTrfTxInf/PmtTpInf/InstrPrty',
        'iso_data_type': 'Priority2Code',
    },
    'purpose_code': {
        'business_name': 'Purpose Code',
        'business_description': 'Per ISO 20022: Underlying reason for the payment transaction as published in external code list.',
        'iso_element_name': 'Code',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/Purp/Cd | Document/FICdtTrf/CdtTrfTxInf/Purp/Cd',
        'iso_data_type': 'ExternalPurpose1Code',
    },
    'purpose_proprietary': {
        'business_name': 'Purpose Proprietary',
        'business_description': 'Per ISO 20022: Proprietary purpose code when no standard code applies.',
        'iso_element_name': 'Proprietary',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/Purp/Prtry | Document/FICdtTrf/CdtTrfTxInf/Purp/Prtry',
        'iso_data_type': 'Max35Text',
    },
    'remittance_unstructured': {
        'business_name': 'Remittance Information Unstructured',
        'business_description': 'Per ISO 20022: Information supplied to enable matching of an entry with items that the transfer is intended to settle.',
        'iso_element_name': 'Unstructured',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/RmtInf/Ustrd | Document/FICdtTrf/CdtTrfTxInf/RmtInf/Ustrd',
        'iso_data_type': 'Max140Text',
    },
    'remittance_structured': {
        'business_name': 'Remittance Information Structured',
        'business_description': 'Per ISO 20022: Structured information that enables matching with items the transfer is intended to settle.',
        'iso_element_name': 'Structured',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/RmtInf/Strd | Document/FICdtTrf/CdtTrfTxInf/RmtInf/Strd',
        'iso_data_type': 'StructuredRemittanceInformation16',
    },
    'regulatory_reporting': {
        'business_name': 'Regulatory Reporting',
        'business_description': 'Per ISO 20022: Information needed due to regulatory requirements.',
        'iso_element_name': 'RegulatoryReporting',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/RgltryRptg | Document/FICdtTrf/CdtTrfTxInf/RgltryRptg',
        'iso_data_type': 'RegulatoryReporting3',
    },
    'tax_information': {
        'business_name': 'Tax Information',
        'business_description': 'Per ISO 20022: Provides details on the tax amount(s) and reason(s).',
        'iso_element_name': 'Tax',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/Tax | Document/FICdtTrf/CdtTrfTxInf/Tax',
        'iso_data_type': 'TaxInformation7',
    },
    'supplementary_data': {
        'business_name': 'Supplementary Data',
        'business_description': 'Per ISO 20022: Additional information that cannot be captured in structured fields.',
        'iso_element_name': 'SupplementaryData',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/SplmtryData | Document/FICdtTrf/SplmtryData | Document/FIToFIPmtStsRpt/SplmtryData | Document/PmtRtr/SplmtryData',
        'iso_data_type': 'SupplementaryData1',
    },
    # Debtor fields
    'debtor_name': {
        'business_name': 'Debtor Name',
        'business_description': 'Per ISO 20022: Name of the party that owes an amount of money to the creditor.',
        'iso_element_name': 'Name',
        'iso_element_path': 'Document/FIToFICstmrCdtTrf/CdtTrfTxInf/Dbtr/Nm | Document/FICdtTrf/CdtTrfTxInf/Dbtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'debtor_party_id': {
        'business_name': 'Debtor Party ID',
        'business_description': 'Reference to the CDM party record for the debtor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'debtor_address_street': {
        'business_name': 'Debtor Street Name',
        'business_description': 'Per ISO 20022: Name of the street or thoroughfare.',
        'iso_element_name': 'StreetName',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/PstlAdr/StrtNm',
        'iso_data_type': 'Max70Text',
    },
    'debtor_address_building': {
        'business_name': 'Debtor Building Number',
        'business_description': 'Per ISO 20022: Number that identifies the position of the building on a street.',
        'iso_element_name': 'BuildingNumber',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/PstlAdr/BldgNb',
        'iso_data_type': 'Max16Text',
    },
    'debtor_address_postal_code': {
        'business_name': 'Debtor Postal Code',
        'business_description': 'Per ISO 20022: Identifier of a group of letters and/or numbers for postal delivery.',
        'iso_element_name': 'PostCode',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/PstlAdr/PstCd',
        'iso_data_type': 'Max16Text',
    },
    'debtor_address_town': {
        'business_name': 'Debtor Town Name',
        'business_description': 'Per ISO 20022: Name of the town, city, or municipality.',
        'iso_element_name': 'TownName',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/PstlAdr/TwnNm',
        'iso_data_type': 'Max35Text',
    },
    'debtor_address_country_subdivision': {
        'business_name': 'Debtor Country Subdivision',
        'business_description': 'Per ISO 20022: Identifies a subdivision of a country (state, province, region).',
        'iso_element_name': 'CountrySubDivision',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/PstlAdr/CtrySubDvsn',
        'iso_data_type': 'Max35Text',
    },
    'debtor_address_country': {
        'business_name': 'Debtor Country',
        'business_description': 'Per ISO 20022: Nation with its own government (ISO 3166-1 alpha-2).',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'debtor_address_lines': {
        'business_name': 'Debtor Address Lines',
        'business_description': 'Per ISO 20022: Unstructured address lines when structured format is not available.',
        'iso_element_name': 'AddressLine',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/PstlAdr/AdrLine',
        'iso_data_type': 'Max70Text',
    },
    'debtor_id_org_bic': {
        'business_name': 'Debtor Organisation BIC',
        'business_description': 'Per ISO 20022: Business Identifier Code (BIC) of the debtor organisation.',
        'iso_element_name': 'AnyBIC',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/Id/OrgId/AnyBIC',
        'iso_data_type': 'AnyBICDec2014Identifier',
    },
    'debtor_id_org_lei': {
        'business_name': 'Debtor Organisation LEI',
        'business_description': 'Per ISO 20022: Legal Entity Identifier of the debtor organisation.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/Id/OrgId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'debtor_id_org_other': {
        'business_name': 'Debtor Organisation Other ID',
        'business_description': 'Per ISO 20022: Other identification of the debtor organisation.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/Id/OrgId/Othr/Id',
        'iso_data_type': 'Max35Text',
    },
    'debtor_id_org_other_scheme': {
        'business_name': 'Debtor Organisation ID Scheme',
        'business_description': 'Per ISO 20022: Scheme name for the other organisation identification.',
        'iso_element_name': 'SchemeName',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/Id/OrgId/Othr/SchmeNm',
        'iso_data_type': 'OrganisationIdentificationSchemeName1Choice',
    },
    'debtor_id_private_birth_date': {
        'business_name': 'Debtor Birth Date',
        'business_description': 'Per ISO 20022: Date of birth of the debtor (private individual).',
        'iso_element_name': 'BirthDate',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/Id/PrvtId/DtAndPlcOfBirth/BirthDt',
        'iso_data_type': 'ISODate',
    },
    'debtor_id_private_birth_country': {
        'business_name': 'Debtor Birth Country',
        'business_description': 'Per ISO 20022: Country of birth of the debtor.',
        'iso_element_name': 'CountryOfBirth',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/Id/PrvtId/DtAndPlcOfBirth/CtryOfBirth',
        'iso_data_type': 'CountryCode',
    },
    'debtor_id_private_other': {
        'business_name': 'Debtor Private Other ID',
        'business_description': 'Per ISO 20022: Other identification of the debtor (private individual).',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/Dbtr/Id/PrvtId/Othr/Id',
        'iso_data_type': 'Max35Text',
    },
    # Debtor Account fields
    'debtor_account_id': {
        'business_name': 'Debtor Account IBAN',
        'business_description': 'Per ISO 20022: International Bank Account Number (IBAN) of the debtor account.',
        'iso_element_name': 'IBAN',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Id/IBAN',
        'iso_data_type': 'IBAN2007Identifier',
    },
    'debtor_account_other': {
        'business_name': 'Debtor Account Other ID',
        'business_description': 'Per ISO 20022: Other identification of the debtor account (non-IBAN).',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Id/Othr/Id',
        'iso_data_type': 'Max34Text',
    },
    'debtor_account_other_scheme': {
        'business_name': 'Debtor Account ID Scheme',
        'business_description': 'Per ISO 20022: Scheme name for the other account identification.',
        'iso_element_name': 'SchemeName',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Id/Othr/SchmeNm',
        'iso_data_type': 'AccountSchemeName1Choice',
    },
    'debtor_account_type': {
        'business_name': 'Debtor Account Type',
        'business_description': 'Per ISO 20022: Type of account. CACC=Current, SVGS=Savings, LOAN=Loan.',
        'iso_element_name': 'Code',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Tp/Cd',
        'iso_data_type': 'ExternalCashAccountType1Code',
    },
    'debtor_account_currency': {
        'business_name': 'Debtor Account Currency',
        'business_description': 'Per ISO 20022: Currency of the debtor account.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Ccy',
        'iso_data_type': 'ActiveOrHistoricCurrencyCode',
    },
    'debtor_account_name': {
        'business_name': 'Debtor Account Name',
        'business_description': 'Per ISO 20022: Name of the debtor account.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Nm',
        'iso_data_type': 'Max70Text',
    },
    'debtor_account_proxy_type': {
        'business_name': 'Debtor Account Proxy Type',
        'business_description': 'Per ISO 20022: Type of proxy used to identify the account (email, phone, etc.).',
        'iso_element_name': 'Type',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Prxy/Tp',
        'iso_data_type': 'ProxyAccountType1Choice',
    },
    'debtor_account_proxy_id': {
        'business_name': 'Debtor Account Proxy ID',
        'business_description': 'Per ISO 20022: Proxy identification of the account.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/DbtrAcct/Prxy/Id',
        'iso_data_type': 'Max2048Text',
    },
    # Debtor Agent fields
    'debtor_agent_bic': {
        'business_name': 'Debtor Agent BIC',
        'business_description': 'Per ISO 20022: Business Identifier Code of the debtor agent (debtor bank).',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'debtor_agent_fi_id': {
        'business_name': 'Debtor Agent Financial Institution ID',
        'business_description': 'Reference to the CDM financial institution record for the debtor agent.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'debtor_agent_clearing_system': {
        'business_name': 'Debtor Agent Clearing System',
        'business_description': 'Per ISO 20022: Clearing system identification for the debtor agent.',
        'iso_element_name': 'Code',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/ClrSysMmbId/ClrSysId/Cd',
        'iso_data_type': 'ExternalClearingSystemIdentification1Code',
    },
    'debtor_agent_clearing_id': {
        'business_name': 'Debtor Agent Clearing Member ID',
        'business_description': 'Per ISO 20022: Identification of the debtor agent as a member of a clearing system.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'debtor_agent_lei': {
        'business_name': 'Debtor Agent LEI',
        'business_description': 'Per ISO 20022: Legal Entity Identifier of the debtor agent.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'debtor_agent_name': {
        'business_name': 'Debtor Agent Name',
        'business_description': 'Per ISO 20022: Name of the debtor agent financial institution.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'debtor_agent_address_street': {
        'business_name': 'Debtor Agent Street',
        'business_description': 'Per ISO 20022: Street name of the debtor agent address.',
        'iso_element_name': 'StreetName',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/PstlAdr/StrtNm',
        'iso_data_type': 'Max70Text',
    },
    'debtor_agent_address_town': {
        'business_name': 'Debtor Agent Town',
        'business_description': 'Per ISO 20022: Town name of the debtor agent address.',
        'iso_element_name': 'TownName',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/PstlAdr/TwnNm',
        'iso_data_type': 'Max35Text',
    },
    'debtor_agent_address_country': {
        'business_name': 'Debtor Agent Country',
        'business_description': 'Per ISO 20022: Country of the debtor agent.',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'debtor_agent_branch_id': {
        'business_name': 'Debtor Agent Branch ID',
        'business_description': 'Per ISO 20022: Identification of the branch of the debtor agent.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/DbtrAgt/BrnchId/Id',
        'iso_data_type': 'Max35Text',
    },
    # Creditor fields
    'creditor_name': {
        'business_name': 'Creditor Name',
        'business_description': 'Per ISO 20022: Name of the party to which an amount of money is due.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'creditor_party_id': {
        'business_name': 'Creditor Party ID',
        'business_description': 'Reference to the CDM party record for the creditor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'creditor_address_street': {
        'business_name': 'Creditor Street Name',
        'business_description': 'Per ISO 20022: Name of the street or thoroughfare.',
        'iso_element_name': 'StreetName',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/PstlAdr/StrtNm',
        'iso_data_type': 'Max70Text',
    },
    'creditor_address_building': {
        'business_name': 'Creditor Building Number',
        'business_description': 'Per ISO 20022: Building number of the creditor address.',
        'iso_element_name': 'BuildingNumber',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/PstlAdr/BldgNb',
        'iso_data_type': 'Max16Text',
    },
    'creditor_address_postal_code': {
        'business_name': 'Creditor Postal Code',
        'business_description': 'Per ISO 20022: Postal code of the creditor address.',
        'iso_element_name': 'PostCode',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/PstlAdr/PstCd',
        'iso_data_type': 'Max16Text',
    },
    'creditor_address_town': {
        'business_name': 'Creditor Town Name',
        'business_description': 'Per ISO 20022: Town name of the creditor address.',
        'iso_element_name': 'TownName',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/PstlAdr/TwnNm',
        'iso_data_type': 'Max35Text',
    },
    'creditor_address_country_subdivision': {
        'business_name': 'Creditor Country Subdivision',
        'business_description': 'Per ISO 20022: State/province of the creditor address.',
        'iso_element_name': 'CountrySubDivision',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/PstlAdr/CtrySubDvsn',
        'iso_data_type': 'Max35Text',
    },
    'creditor_address_country': {
        'business_name': 'Creditor Country',
        'business_description': 'Per ISO 20022: Country of the creditor (ISO 3166-1 alpha-2).',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'creditor_address_lines': {
        'business_name': 'Creditor Address Lines',
        'business_description': 'Per ISO 20022: Unstructured address lines for the creditor.',
        'iso_element_name': 'AddressLine',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/PstlAdr/AdrLine',
        'iso_data_type': 'Max70Text',
    },
    'creditor_id_org_bic': {
        'business_name': 'Creditor Organisation BIC',
        'business_description': 'Per ISO 20022: BIC of the creditor organisation.',
        'iso_element_name': 'AnyBIC',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Id/OrgId/AnyBIC',
        'iso_data_type': 'AnyBICDec2014Identifier',
    },
    'creditor_id_org_lei': {
        'business_name': 'Creditor Organisation LEI',
        'business_description': 'Per ISO 20022: Legal Entity Identifier of the creditor organisation.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Id/OrgId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'creditor_id_org_other': {
        'business_name': 'Creditor Organisation Other ID',
        'business_description': 'Per ISO 20022: Other identification of the creditor organisation.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Id/OrgId/Othr/Id',
        'iso_data_type': 'Max35Text',
    },
    'creditor_id_org_other_scheme': {
        'business_name': 'Creditor Organisation ID Scheme',
        'business_description': 'Per ISO 20022: Scheme name for the other creditor organisation ID.',
        'iso_element_name': 'SchemeName',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Id/OrgId/Othr/SchmeNm',
        'iso_data_type': 'OrganisationIdentificationSchemeName1Choice',
    },
    'creditor_id_private_birth_date': {
        'business_name': 'Creditor Birth Date',
        'business_description': 'Per ISO 20022: Date of birth of the creditor (private individual).',
        'iso_element_name': 'BirthDate',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Id/PrvtId/DtAndPlcOfBirth/BirthDt',
        'iso_data_type': 'ISODate',
    },
    'creditor_id_private_birth_country': {
        'business_name': 'Creditor Birth Country',
        'business_description': 'Per ISO 20022: Country of birth of the creditor.',
        'iso_element_name': 'CountryOfBirth',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Id/PrvtId/DtAndPlcOfBirth/CtryOfBirth',
        'iso_data_type': 'CountryCode',
    },
    'creditor_id_private_other': {
        'business_name': 'Creditor Private Other ID',
        'business_description': 'Per ISO 20022: Other identification of the creditor (private individual).',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/Cdtr/Id/PrvtId/Othr/Id',
        'iso_data_type': 'Max35Text',
    },
    # Creditor Account fields
    'creditor_account_id': {
        'business_name': 'Creditor Account IBAN',
        'business_description': 'Per ISO 20022: IBAN of the creditor account.',
        'iso_element_name': 'IBAN',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Id/IBAN',
        'iso_data_type': 'IBAN2007Identifier',
    },
    'creditor_account_other': {
        'business_name': 'Creditor Account Other ID',
        'business_description': 'Per ISO 20022: Other identification of the creditor account.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Id/Othr/Id',
        'iso_data_type': 'Max34Text',
    },
    'creditor_account_other_scheme': {
        'business_name': 'Creditor Account ID Scheme',
        'business_description': 'Per ISO 20022: Scheme name for the other account identification.',
        'iso_element_name': 'SchemeName',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Id/Othr/SchmeNm',
        'iso_data_type': 'AccountSchemeName1Choice',
    },
    'creditor_account_type': {
        'business_name': 'Creditor Account Type',
        'business_description': 'Per ISO 20022: Type of creditor account.',
        'iso_element_name': 'Code',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Tp/Cd',
        'iso_data_type': 'ExternalCashAccountType1Code',
    },
    'creditor_account_currency': {
        'business_name': 'Creditor Account Currency',
        'business_description': 'Per ISO 20022: Currency of the creditor account.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Ccy',
        'iso_data_type': 'ActiveOrHistoricCurrencyCode',
    },
    'creditor_account_name': {
        'business_name': 'Creditor Account Name',
        'business_description': 'Per ISO 20022: Name of the creditor account.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Nm',
        'iso_data_type': 'Max70Text',
    },
    'creditor_account_proxy_type': {
        'business_name': 'Creditor Account Proxy Type',
        'business_description': 'Per ISO 20022: Type of proxy used to identify the creditor account.',
        'iso_element_name': 'Type',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Prxy/Tp',
        'iso_data_type': 'ProxyAccountType1Choice',
    },
    'creditor_account_proxy_id': {
        'business_name': 'Creditor Account Proxy ID',
        'business_description': 'Per ISO 20022: Proxy identification of the creditor account.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/CdtrAcct/Prxy/Id',
        'iso_data_type': 'Max2048Text',
    },
    # Creditor Agent fields
    'creditor_agent_bic': {
        'business_name': 'Creditor Agent BIC',
        'business_description': 'Per ISO 20022: BIC of the creditor agent (creditor bank).',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'creditor_agent_fi_id': {
        'business_name': 'Creditor Agent Financial Institution ID',
        'business_description': 'Reference to the CDM financial institution record for the creditor agent.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'creditor_agent_clearing_system': {
        'business_name': 'Creditor Agent Clearing System',
        'business_description': 'Per ISO 20022: Clearing system identification for the creditor agent.',
        'iso_element_name': 'Code',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/ClrSysMmbId/ClrSysId/Cd',
        'iso_data_type': 'ExternalClearingSystemIdentification1Code',
    },
    'creditor_agent_clearing_id': {
        'business_name': 'Creditor Agent Clearing Member ID',
        'business_description': 'Per ISO 20022: Clearing member ID of the creditor agent.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'creditor_agent_lei': {
        'business_name': 'Creditor Agent LEI',
        'business_description': 'Per ISO 20022: Legal Entity Identifier of the creditor agent.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'creditor_agent_name': {
        'business_name': 'Creditor Agent Name',
        'business_description': 'Per ISO 20022: Name of the creditor agent financial institution.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'creditor_agent_address_street': {
        'business_name': 'Creditor Agent Street',
        'business_description': 'Per ISO 20022: Street of the creditor agent address.',
        'iso_element_name': 'StreetName',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/PstlAdr/StrtNm',
        'iso_data_type': 'Max70Text',
    },
    'creditor_agent_address_town': {
        'business_name': 'Creditor Agent Town',
        'business_description': 'Per ISO 20022: Town of the creditor agent address.',
        'iso_element_name': 'TownName',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/PstlAdr/TwnNm',
        'iso_data_type': 'Max35Text',
    },
    'creditor_agent_address_country': {
        'business_name': 'Creditor Agent Country',
        'business_description': 'Per ISO 20022: Country of the creditor agent.',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'creditor_agent_branch_id': {
        'business_name': 'Creditor Agent Branch ID',
        'business_description': 'Per ISO 20022: Branch identification of the creditor agent.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/CdtrAgt/BrnchId/Id',
        'iso_data_type': 'Max35Text',
    },
    # Instructing/Instructed Agent fields
    'instructing_agent_bic': {
        'business_name': 'Instructing Agent BIC',
        'business_description': 'Per ISO 20022: BIC of the agent that instructs the next party in the chain.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'GrpHdr/InstgAgt/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'instructing_agent_fi_id': {
        'business_name': 'Instructing Agent Financial Institution ID',
        'business_description': 'Reference to the CDM financial institution record for the instructing agent.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'instructing_agent_clearing_id': {
        'business_name': 'Instructing Agent Clearing ID',
        'business_description': 'Per ISO 20022: Clearing system member ID of the instructing agent.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'GrpHdr/InstgAgt/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'instructing_agent_lei': {
        'business_name': 'Instructing Agent LEI',
        'business_description': 'Per ISO 20022: Legal Entity Identifier of the instructing agent.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'GrpHdr/InstgAgt/FinInstnId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'instructing_agent_name': {
        'business_name': 'Instructing Agent Name',
        'business_description': 'Per ISO 20022: Name of the instructing agent.',
        'iso_element_name': 'Name',
        'iso_element_path': 'GrpHdr/InstgAgt/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'instructing_agent_country': {
        'business_name': 'Instructing Agent Country',
        'business_description': 'Per ISO 20022: Country of the instructing agent.',
        'iso_element_name': 'Country',
        'iso_element_path': 'GrpHdr/InstgAgt/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'instructed_agent_bic': {
        'business_name': 'Instructed Agent BIC',
        'business_description': 'Per ISO 20022: BIC of the agent that receives the instruction.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'GrpHdr/InstdAgt/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'instructed_agent_fi_id': {
        'business_name': 'Instructed Agent Financial Institution ID',
        'business_description': 'Reference to the CDM financial institution record for the instructed agent.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'instructed_agent_clearing_id': {
        'business_name': 'Instructed Agent Clearing ID',
        'business_description': 'Per ISO 20022: Clearing system member ID of the instructed agent.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'GrpHdr/InstdAgt/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'instructed_agent_lei': {
        'business_name': 'Instructed Agent LEI',
        'business_description': 'Per ISO 20022: Legal Entity Identifier of the instructed agent.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'GrpHdr/InstdAgt/FinInstnId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'instructed_agent_name': {
        'business_name': 'Instructed Agent Name',
        'business_description': 'Per ISO 20022: Name of the instructed agent.',
        'iso_element_name': 'Name',
        'iso_element_path': 'GrpHdr/InstdAgt/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'instructed_agent_country': {
        'business_name': 'Instructed Agent Country',
        'business_description': 'Per ISO 20022: Country of the instructed agent.',
        'iso_element_name': 'Country',
        'iso_element_path': 'GrpHdr/InstdAgt/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    # Intermediary Agent fields
    'intermediary_agent1_bic': {
        'business_name': 'Intermediary Agent 1 BIC',
        'business_description': 'Per ISO 20022: BIC of the first intermediary agent between debtor agent and creditor agent.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'intermediary_agent1_fi_id': {
        'business_name': 'Intermediary Agent 1 FI ID',
        'business_description': 'Reference to CDM financial institution record for intermediary agent 1.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'intermediary_agent1_clearing_id': {
        'business_name': 'Intermediary Agent 1 Clearing ID',
        'business_description': 'Per ISO 20022: Clearing member ID of intermediary agent 1.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'intermediary_agent1_lei': {
        'business_name': 'Intermediary Agent 1 LEI',
        'business_description': 'Per ISO 20022: LEI of intermediary agent 1.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'intermediary_agent1_name': {
        'business_name': 'Intermediary Agent 1 Name',
        'business_description': 'Per ISO 20022: Name of intermediary agent 1.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'intermediary_agent1_country': {
        'business_name': 'Intermediary Agent 1 Country',
        'business_description': 'Per ISO 20022: Country of intermediary agent 1.',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt1/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'intermediary_agent1_account': {
        'business_name': 'Intermediary Agent 1 Account',
        'business_description': 'Per ISO 20022: Account of intermediary agent 1.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt1Acct/Id',
        'iso_data_type': 'AccountIdentification4Choice',
    },
    'intermediary_agent2_bic': {
        'business_name': 'Intermediary Agent 2 BIC',
        'business_description': 'Per ISO 20022: BIC of the second intermediary agent.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt2/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'intermediary_agent2_fi_id': {
        'business_name': 'Intermediary Agent 2 FI ID',
        'business_description': 'Reference to CDM financial institution record for intermediary agent 2.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'intermediary_agent2_clearing_id': {
        'business_name': 'Intermediary Agent 2 Clearing ID',
        'business_description': 'Per ISO 20022: Clearing member ID of intermediary agent 2.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt2/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'intermediary_agent2_lei': {
        'business_name': 'Intermediary Agent 2 LEI',
        'business_description': 'Per ISO 20022: LEI of intermediary agent 2.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt2/FinInstnId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'intermediary_agent2_name': {
        'business_name': 'Intermediary Agent 2 Name',
        'business_description': 'Per ISO 20022: Name of intermediary agent 2.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt2/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'intermediary_agent2_country': {
        'business_name': 'Intermediary Agent 2 Country',
        'business_description': 'Per ISO 20022: Country of intermediary agent 2.',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt2/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'intermediary_agent2_account': {
        'business_name': 'Intermediary Agent 2 Account',
        'business_description': 'Per ISO 20022: Account of intermediary agent 2.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt2Acct/Id',
        'iso_data_type': 'AccountIdentification4Choice',
    },
    'intermediary_agent3_bic': {
        'business_name': 'Intermediary Agent 3 BIC',
        'business_description': 'Per ISO 20022: BIC of the third intermediary agent.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt3/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'intermediary_agent3_fi_id': {
        'business_name': 'Intermediary Agent 3 FI ID',
        'business_description': 'Reference to CDM financial institution record for intermediary agent 3.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'intermediary_agent3_clearing_id': {
        'business_name': 'Intermediary Agent 3 Clearing ID',
        'business_description': 'Per ISO 20022: Clearing member ID of intermediary agent 3.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt3/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'intermediary_agent3_country': {
        'business_name': 'Intermediary Agent 3 Country',
        'business_description': 'Per ISO 20022: Country of intermediary agent 3.',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/IntrmyAgt3/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    # Ultimate Debtor/Creditor fields
    'ultimate_debtor_name': {
        'business_name': 'Ultimate Debtor Name',
        'business_description': 'Per ISO 20022: Ultimate party that owes an amount of money to the creditor.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/UltmtDbtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'ultimate_debtor_party_id': {
        'business_name': 'Ultimate Debtor Party ID',
        'business_description': 'Reference to CDM party record for the ultimate debtor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'ultimate_debtor_id': {
        'business_name': 'Ultimate Debtor Identification',
        'business_description': 'Per ISO 20022: Identification of the ultimate debtor.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/UltmtDbtr/Id',
        'iso_data_type': 'Party38Choice',
    },
    'ultimate_debtor_address_country': {
        'business_name': 'Ultimate Debtor Country',
        'business_description': 'Per ISO 20022: Country of the ultimate debtor.',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/UltmtDbtr/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'ultimate_creditor_name': {
        'business_name': 'Ultimate Creditor Name',
        'business_description': 'Per ISO 20022: Ultimate party to which an amount of money is due.',
        'iso_element_name': 'Name',
        'iso_element_path': 'CdtTrfTxInf/UltmtCdtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'ultimate_creditor_party_id': {
        'business_name': 'Ultimate Creditor Party ID',
        'business_description': 'Reference to CDM party record for the ultimate creditor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'ultimate_creditor_id': {
        'business_name': 'Ultimate Creditor Identification',
        'business_description': 'Per ISO 20022: Identification of the ultimate creditor.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'CdtTrfTxInf/UltmtCdtr/Id',
        'iso_data_type': 'Party38Choice',
    },
    'ultimate_creditor_address_country': {
        'business_name': 'Ultimate Creditor Country',
        'business_description': 'Per ISO 20022: Country of the ultimate creditor.',
        'iso_element_name': 'Country',
        'iso_element_path': 'CdtTrfTxInf/UltmtCdtr/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    # Charges fields
    'charges_amount': {
        'business_name': 'Charges Amount',
        'business_description': 'Per ISO 20022: Amount of money asked or paid for the charge.',
        'iso_element_name': 'Amount',
        'iso_element_path': 'CdtTrfTxInf/ChrgsInf/Amt',
        'iso_data_type': 'ActiveOrHistoricCurrencyAndAmount',
    },
    'charges_currency': {
        'business_name': 'Charges Currency',
        'business_description': 'Per ISO 20022: Currency of the charges amount.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'CdtTrfTxInf/ChrgsInf/Amt/@Ccy',
        'iso_data_type': 'ActiveOrHistoricCurrencyCode',
    },
    'charges_agent_bic': {
        'business_name': 'Charges Agent BIC',
        'business_description': 'Per ISO 20022: BIC of the agent that charges the fee.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'CdtTrfTxInf/ChrgsInf/Agt/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    # Total amounts
    'total_interbank_settlement_amount': {
        'business_name': 'Total Interbank Settlement Amount',
        'business_description': 'Per ISO 20022: Total amount of money moved between instructing and instructed agents.',
        'iso_element_name': 'TotalInterbankSettlementAmount',
        'iso_element_path': 'GrpHdr/TtlIntrBkSttlmAmt',
        'iso_data_type': 'ActiveCurrencyAndAmount',
    },
    'total_interbank_settlement_currency': {
        'business_name': 'Total Interbank Settlement Currency',
        'business_description': 'Per ISO 20022: Currency of the total interbank settlement amount.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'GrpHdr/TtlIntrBkSttlmAmt/@Ccy',
        'iso_data_type': 'ActiveCurrencyCode',
    },
    # Scheme/Source fields
    'scheme_identifiers': {
        'business_name': 'Scheme Identifiers',
        'business_description': 'Identifies the payment scheme(s) applicable to this transaction.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'source_format': {
        'business_name': 'Source Format',
        'business_description': 'Original message format from which this record was derived.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'source_stg_table': {
        'business_name': 'Source Staging Table',
        'business_description': 'Silver layer staging table from which this record was derived.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'stg_id': {
        'business_name': 'Staging ID',
        'business_description': 'Reference to the Silver layer staging record.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'raw_id': {
        'business_name': 'Raw ID',
        'business_description': 'Reference to the Bronze layer raw record.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'batch_id': {
        'business_name': 'Batch ID',
        'business_description': 'Identifier of the processing batch.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'processing_status': {
        'business_name': 'Processing Status',
        'business_description': 'Current processing status in the CDM pipeline.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
}

# pacs.008 - FI to FI Customer Credit Transfer
CDM_PACS_FI_CUSTOMER_CREDIT_TRANSFER = {
    'cdm_pacs_fi_customer_credit_transfer': _COMMON_PACS_FIELDS,
}

# pacs.009 - FI Credit Transfer
CDM_PACS_FI_CREDIT_TRANSFER = {
    'cdm_pacs_fi_credit_transfer': _COMMON_PACS_FIELDS,
}

# pacs.002 - Payment Status Report
CDM_PACS_FI_PAYMENT_STATUS_REPORT = {
    'cdm_pacs_fi_payment_status_report': {
        **{k: v for k, v in _COMMON_PACS_FIELDS.items() if k in [
            'instruction_id', 'message_id', 'creation_datetime', 'end_to_end_id',
            'transaction_id', 'uetr', 'clearing_system_reference', 'stg_id', 'raw_id',
            'batch_id', 'processing_status', 'source_format', 'source_stg_table',
            'instructed_agent_fi_id', 'instructing_agent_fi_id', 'supplementary_data'
        ]},
        'original_message_id': {
            'business_name': 'Original Message Identification',
            'business_description': 'Per ISO 20022: Point-to-point reference of the original message.',
            'iso_element_name': 'OrgnlMsgId',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/OrgnlMsgId',
            'iso_data_type': 'Max35Text',
        },
        'original_message_name_id': {
            'business_name': 'Original Message Name',
            'business_description': 'Per ISO 20022: Specifies the original message name identifier.',
            'iso_element_name': 'OrgnlMsgNmId',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/OrgnlMsgNmId',
            'iso_data_type': 'Max35Text',
        },
        'group_status': {
            'business_name': 'Group Status',
            'business_description': 'Per ISO 20022: Status of a group of transactions. ACTC, ACCP, ACSP, ACSC, RJCT, etc.',
            'iso_element_name': 'GroupStatus',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/GrpSts',
            'iso_data_type': 'ExternalPaymentGroupStatus1Code',
        },
        'transaction_status': {
            'business_name': 'Transaction Status',
            'business_description': 'Per ISO 20022: Status of an individual transaction.',
            'iso_element_name': 'TransactionStatus',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/TxSts',
            'iso_data_type': 'ExternalPaymentTransactionStatus1Code',
        },
        'status_reason_code': {
            'business_name': 'Status Reason Code',
            'business_description': 'Per ISO 20022: Reason for the status, as published in external code list.',
            'iso_element_name': 'Code',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/StsRsnInf/Rsn/Cd',
            'iso_data_type': 'ExternalStatusReason1Code',
        },
        'status_reason_proprietary': {
            'business_name': 'Status Reason Proprietary',
            'business_description': 'Per ISO 20022: Proprietary status reason.',
            'iso_element_name': 'Proprietary',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/StsRsnInf/Rsn/Prtry',
            'iso_data_type': 'Max35Text',
        },
        'status_additional_info': {
            'business_name': 'Additional Status Information',
            'business_description': 'Per ISO 20022: Additional information about the status.',
            'iso_element_name': 'AdditionalInformation',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/StsRsnInf/AddtlInf',
            'iso_data_type': 'Max105Text',
        },
        'acceptance_datetime': {
            'business_name': 'Acceptance Date Time',
            'business_description': 'Per ISO 20022: Date and time at which the status was determined.',
            'iso_element_name': 'AcceptanceDateTime',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/AccptncDtTm',
            'iso_data_type': 'ISODateTime',
        },
        # Additional status report fields
        'status_report_id': {
            'business_name': 'Status Report ID',
            'business_description': 'Unique identifier for this status report in the CDM.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'status_id': {
            'business_name': 'Status ID',
            'business_description': 'Per ISO 20022: Unique identification of the status information.',
            'iso_element_name': 'StatusIdentification',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/StsId',
            'iso_data_type': 'Max35Text',
        },
        'account_servicer_reference': {
            'business_name': 'Account Servicer Reference',
            'business_description': 'Per ISO 20022: Reference assigned by the account servicer.',
            'iso_element_name': 'AccountServicerReference',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/AcctSvcrRef',
            'iso_data_type': 'Max35Text',
        },
        'effective_settlement_date': {
            'business_name': 'Effective Settlement Date',
            'business_description': 'Per ISO 20022: Date on which the settlement took effect.',
            'iso_element_name': 'EffectiveInterbankSettlementDate',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/FctvIntrBkSttlmDt/Dt',
            'iso_data_type': 'ISODate',
        },
        'group_status_reason_code': {
            'business_name': 'Group Status Reason Code',
            'business_description': 'Per ISO 20022: Reason for the group status as per external code list.',
            'iso_element_name': 'Code',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/StsRsnInf/Rsn/Cd',
            'iso_data_type': 'ExternalStatusReason1Code',
        },
        'group_status_reason_proprietary': {
            'business_name': 'Group Status Reason Proprietary',
            'business_description': 'Per ISO 20022: Proprietary reason for the group status.',
            'iso_element_name': 'Proprietary',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/StsRsnInf/Rsn/Prtry',
            'iso_data_type': 'Max35Text',
        },
        'group_status_reason_info': {
            'business_name': 'Group Status Reason Information',
            'business_description': 'Per ISO 20022: Complete group status reason information block as JSON.',
            'iso_element_name': 'StatusReasonInformation',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/StsRsnInf',
            'iso_data_type': 'StatusReasonInformation12',
        },
        'status_reason_info': {
            'business_name': 'Status Reason Information',
            'business_description': 'Per ISO 20022: Complete transaction status reason information block as JSON.',
            'iso_element_name': 'StatusReasonInformation',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/StsRsnInf',
            'iso_data_type': 'StatusReasonInformation12',
        },
        # Original Payment Information
        'original_creation_datetime': {
            'business_name': 'Original Creation Date Time',
            'business_description': 'Per ISO 20022: Creation date and time of the original message.',
            'iso_element_name': 'OrgnlCreDtTm',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/OrgnlCreDtTm',
            'iso_data_type': 'ISODateTime',
        },
        'original_number_of_transactions': {
            'business_name': 'Original Number of Transactions',
            'business_description': 'Per ISO 20022: Number of transactions in the original message.',
            'iso_element_name': 'OrgnlNbOfTxs',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/OrgnlGrpInfAndSts/OrgnlNbOfTxs',
            'iso_data_type': 'Max15NumericText',
        },
        'original_end_to_end_id': {
            'business_name': 'Original End to End ID',
            'business_description': 'Per ISO 20022: End-to-end ID of the original payment.',
            'iso_element_name': 'OrgnlEndToEndId',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlEndToEndId',
            'iso_data_type': 'Max35Text',
        },
        'original_instruction_id': {
            'business_name': 'Original Instruction ID',
            'business_description': 'Per ISO 20022: Instruction ID of the original payment.',
            'iso_element_name': 'OrgnlInstrId',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlInstrId',
            'iso_data_type': 'Max35Text',
        },
        'original_transaction_id': {
            'business_name': 'Original Transaction ID',
            'business_description': 'Per ISO 20022: Transaction ID of the original payment.',
            'iso_element_name': 'OrgnlTxId',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxId',
            'iso_data_type': 'Max35Text',
        },
        'original_uetr': {
            'business_name': 'Original UETR',
            'business_description': 'Per ISO 20022: UETR of the original payment.',
            'iso_element_name': 'OrgnlUETR',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlUETR',
            'iso_data_type': 'UUIDv4Identifier',
        },
        'original_settlement_amount': {
            'business_name': 'Original Settlement Amount',
            'business_description': 'Per ISO 20022: Settlement amount of the original payment.',
            'iso_element_name': 'OrgnlIntrBkSttlmAmt',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/IntrBkSttlmAmt',
            'iso_data_type': 'ActiveCurrencyAndAmount',
        },
        'original_settlement_currency': {
            'business_name': 'Original Settlement Currency',
            'business_description': 'Per ISO 20022: Currency of the original settlement amount.',
            'iso_element_name': 'Currency',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/IntrBkSttlmAmt/@Ccy',
            'iso_data_type': 'ActiveCurrencyCode',
        },
        'original_settlement_date': {
            'business_name': 'Original Settlement Date',
            'business_description': 'Per ISO 20022: Settlement date of the original payment.',
            'iso_element_name': 'IntrBkSttlmDt',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/IntrBkSttlmDt',
            'iso_data_type': 'ISODate',
        },
        'original_requested_execution_date': {
            'business_name': 'Original Requested Execution Date',
            'business_description': 'Per ISO 20022: Requested execution date of the original payment.',
            'iso_element_name': 'RequestedExecutionDate',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/ReqdExctnDt/Dt',
            'iso_data_type': 'ISODate',
        },
        # Original Party Information
        'original_debtor_name': {
            'business_name': 'Original Debtor Name',
            'business_description': 'Per ISO 20022: Name of the debtor from the original payment.',
            'iso_element_name': 'Name',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/Dbtr/Nm',
            'iso_data_type': 'Max140Text',
        },
        'original_debtor_party_id': {
            'business_name': 'Original Debtor Party ID',
            'business_description': 'Reference to CDM party record for the original debtor.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_debtor_account_id': {
            'business_name': 'Original Debtor Account ID',
            'business_description': 'Reference to CDM account record for the original debtor account.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_debtor_account_iban': {
            'business_name': 'Original Debtor Account IBAN',
            'business_description': 'Per ISO 20022: IBAN of the original debtor account.',
            'iso_element_name': 'IBAN',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/DbtrAcct/Id/IBAN',
            'iso_data_type': 'IBAN2007Identifier',
        },
        'original_debtor_account_other': {
            'business_name': 'Original Debtor Account Other',
            'business_description': 'Per ISO 20022: Non-IBAN account identification of the original debtor.',
            'iso_element_name': 'Identification',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/DbtrAcct/Id/Othr/Id',
            'iso_data_type': 'Max34Text',
        },
        'original_debtor_agent_bic': {
            'business_name': 'Original Debtor Agent BIC',
            'business_description': 'Per ISO 20022: BIC of the original debtor agent.',
            'iso_element_name': 'BICFI',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/DbtrAgt/FinInstnId/BICFI',
            'iso_data_type': 'BICFIDec2014Identifier',
        },
        'original_debtor_agent_fi_id': {
            'business_name': 'Original Debtor Agent FI ID',
            'business_description': 'Reference to CDM financial institution record for the original debtor agent.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_creditor_name': {
            'business_name': 'Original Creditor Name',
            'business_description': 'Per ISO 20022: Name of the creditor from the original payment.',
            'iso_element_name': 'Name',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/Cdtr/Nm',
            'iso_data_type': 'Max140Text',
        },
        'original_creditor_party_id': {
            'business_name': 'Original Creditor Party ID',
            'business_description': 'Reference to CDM party record for the original creditor.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_creditor_account_id': {
            'business_name': 'Original Creditor Account ID',
            'business_description': 'Reference to CDM account record for the original creditor account.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_creditor_account_iban': {
            'business_name': 'Original Creditor Account IBAN',
            'business_description': 'Per ISO 20022: IBAN of the original creditor account.',
            'iso_element_name': 'IBAN',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/CdtrAcct/Id/IBAN',
            'iso_data_type': 'IBAN2007Identifier',
        },
        'original_creditor_account_other': {
            'business_name': 'Original Creditor Account Other',
            'business_description': 'Per ISO 20022: Non-IBAN account identification of the original creditor.',
            'iso_element_name': 'Identification',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/CdtrAcct/Id/Othr/Id',
            'iso_data_type': 'Max34Text',
        },
        'original_creditor_agent_bic': {
            'business_name': 'Original Creditor Agent BIC',
            'business_description': 'Per ISO 20022: BIC of the original creditor agent.',
            'iso_element_name': 'BICFI',
            'iso_element_path': 'Document/FIToFIPmtStsRpt/TxInfAndSts/OrgnlTxRef/CdtrAgt/FinInstnId/BICFI',
            'iso_data_type': 'BICFIDec2014Identifier',
        },
        'original_creditor_agent_fi_id': {
            'business_name': 'Original Creditor Agent FI ID',
            'business_description': 'Reference to CDM financial institution record for the original creditor agent.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'source_stg_id': {
            'business_name': 'Source Staging ID',
            'business_description': 'Reference to the Silver layer staging record.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
    },
}

# pacs.004 - Payment Return
CDM_PACS_PAYMENT_RETURN = {
    'cdm_pacs_payment_return': {
        **{k: v for k, v in _COMMON_PACS_FIELDS.items() if k in [
            'instruction_id', 'message_id', 'creation_datetime', 'settlement_method',
            'interbank_settlement_date', 'interbank_settlement_amount', 'interbank_settlement_currency',
            'end_to_end_id', 'transaction_id', 'uetr', 'clearing_system_reference',
            'stg_id', 'raw_id', 'batch_id', 'processing_status', 'source_format', 'source_stg_table',
            'charge_bearer', 'clearing_system_code', 'instructed_agent_bic', 'instructed_agent_clearing_id',
            'instructed_agent_fi_id', 'instructing_agent_bic', 'instructing_agent_clearing_id',
            'instructing_agent_fi_id', 'number_of_transactions', 'remittance_unstructured', 'supplementary_data'
        ]},
        'original_message_id': {
            'business_name': 'Original Message Identification',
            'business_description': 'Per ISO 20022: Message identification of the original payment being returned.',
            'iso_element_name': 'OrgnlMsgId',
            'iso_element_path': 'Document/PmtRtr/OrgnlGrpInf/OrgnlMsgId',
            'iso_data_type': 'Max35Text',
        },
        'original_message_name_id': {
            'business_name': 'Original Message Name',
            'business_description': 'Per ISO 20022: Message name of the original payment (e.g., pacs.008).',
            'iso_element_name': 'OrgnlMsgNmId',
            'iso_element_path': 'Document/PmtRtr/OrgnlGrpInf/OrgnlMsgNmId',
            'iso_data_type': 'Max35Text',
        },
        'return_reason_code': {
            'business_name': 'Return Reason Code',
            'business_description': 'Per ISO 20022: Reason for the return as per external code list.',
            'iso_element_name': 'Code',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrRsnInf/Rsn/Cd',
            'iso_data_type': 'ExternalReturnReason1Code',
        },
        'return_reason_proprietary': {
            'business_name': 'Return Reason Proprietary',
            'business_description': 'Per ISO 20022: Proprietary return reason code.',
            'iso_element_name': 'Proprietary',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrRsnInf/Rsn/Prtry',
            'iso_data_type': 'Max35Text',
        },
        'return_additional_info': {
            'business_name': 'Return Additional Information',
            'business_description': 'Per ISO 20022: Additional information about the return reason.',
            'iso_element_name': 'AdditionalInformation',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrRsnInf/AddtlInf',
            'iso_data_type': 'Max105Text',
        },
        'returned_interbank_settlement_amount': {
            'business_name': 'Returned Interbank Settlement Amount',
            'business_description': 'Per ISO 20022: Amount being returned.',
            'iso_element_name': 'RtrdIntrBkSttlmAmt',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrdIntrBkSttlmAmt',
            'iso_data_type': 'ActiveCurrencyAndAmount',
        },
        # Original Payment Information
        'original_clearing_system_reference': {
            'business_name': 'Original Clearing System Reference',
            'business_description': 'Per ISO 20022: Clearing system reference of the original payment.',
            'iso_element_name': 'OrgnlClrSysRef',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlClrSysRef',
            'iso_data_type': 'Max35Text',
        },
        'original_creation_datetime': {
            'business_name': 'Original Creation Date Time',
            'business_description': 'Per ISO 20022: Creation date and time of the original payment.',
            'iso_element_name': 'OrgnlCreDtTm',
            'iso_element_path': 'Document/PmtRtr/OrgnlGrpInf/OrgnlCreDtTm',
            'iso_data_type': 'ISODateTime',
        },
        'original_end_to_end_id': {
            'business_name': 'Original End to End ID',
            'business_description': 'Per ISO 20022: End-to-end ID of the original payment being returned.',
            'iso_element_name': 'OrgnlEndToEndId',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlEndToEndId',
            'iso_data_type': 'Max35Text',
        },
        'original_instruction_id': {
            'business_name': 'Original Instruction ID',
            'business_description': 'Per ISO 20022: Instruction ID of the original payment.',
            'iso_element_name': 'OrgnlInstrId',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlInstrId',
            'iso_data_type': 'Max35Text',
        },
        'original_transaction_id': {
            'business_name': 'Original Transaction ID',
            'business_description': 'Per ISO 20022: Transaction ID of the original payment.',
            'iso_element_name': 'OrgnlTxId',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxId',
            'iso_data_type': 'Max35Text',
        },
        'original_uetr': {
            'business_name': 'Original UETR',
            'business_description': 'Per ISO 20022: UETR of the original payment being returned.',
            'iso_element_name': 'OrgnlUETR',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlUETR',
            'iso_data_type': 'UUIDv4Identifier',
        },
        'original_settlement_amount': {
            'business_name': 'Original Settlement Amount',
            'business_description': 'Per ISO 20022: Settlement amount of the original payment.',
            'iso_element_name': 'OrgnlIntrBkSttlmAmt',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlIntrBkSttlmAmt',
            'iso_data_type': 'ActiveCurrencyAndAmount',
        },
        'original_settlement_currency': {
            'business_name': 'Original Settlement Currency',
            'business_description': 'Per ISO 20022: Currency of the original settlement amount.',
            'iso_element_name': 'Currency',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlIntrBkSttlmAmt/@Ccy',
            'iso_data_type': 'ActiveCurrencyCode',
        },
        'original_settlement_date': {
            'business_name': 'Original Settlement Date',
            'business_description': 'Per ISO 20022: Settlement date of the original payment.',
            'iso_element_name': 'OrgnlIntrBkSttlmDt',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlIntrBkSttlmDt',
            'iso_data_type': 'ISODate',
        },
        # Original Debtor Information
        'original_debtor_name': {
            'business_name': 'Original Debtor Name',
            'business_description': 'Per ISO 20022: Name of the debtor from the original payment.',
            'iso_element_name': 'Name',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/Dbtr/Nm',
            'iso_data_type': 'Max140Text',
        },
        'original_debtor_party_id': {
            'business_name': 'Original Debtor Party ID',
            'business_description': 'Reference to CDM party record for the original debtor.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_debtor_address_country': {
            'business_name': 'Original Debtor Country',
            'business_description': 'Per ISO 20022: Country of the original debtor.',
            'iso_element_name': 'Country',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/Dbtr/PstlAdr/Ctry',
            'iso_data_type': 'CountryCode',
        },
        'original_debtor_account_id': {
            'business_name': 'Original Debtor Account ID',
            'business_description': 'Reference to CDM account record for the original debtor account.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_debtor_account_iban': {
            'business_name': 'Original Debtor Account IBAN',
            'business_description': 'Per ISO 20022: IBAN of the original debtor account.',
            'iso_element_name': 'IBAN',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAcct/Id/IBAN',
            'iso_data_type': 'IBAN2007Identifier',
        },
        'original_debtor_account_other': {
            'business_name': 'Original Debtor Account Other',
            'business_description': 'Per ISO 20022: Non-IBAN account identification of the original debtor.',
            'iso_element_name': 'Identification',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAcct/Id/Othr/Id',
            'iso_data_type': 'Max34Text',
        },
        'original_debtor_agent_bic': {
            'business_name': 'Original Debtor Agent BIC',
            'business_description': 'Per ISO 20022: BIC of the original debtor agent.',
            'iso_element_name': 'BICFI',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/BICFI',
            'iso_data_type': 'BICFIDec2014Identifier',
        },
        'original_debtor_agent_clearing_id': {
            'business_name': 'Original Debtor Agent Clearing ID',
            'business_description': 'Per ISO 20022: Clearing ID of the original debtor agent.',
            'iso_element_name': 'MemberId',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/ClrSysMmbId/MmbId',
            'iso_data_type': 'Max35Text',
        },
        'original_debtor_agent_fi_id': {
            'business_name': 'Original Debtor Agent FI ID',
            'business_description': 'Reference to CDM financial institution record for the original debtor agent.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_debtor_agent_name': {
            'business_name': 'Original Debtor Agent Name',
            'business_description': 'Per ISO 20022: Name of the original debtor agent.',
            'iso_element_name': 'Name',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/DbtrAgt/FinInstnId/Nm',
            'iso_data_type': 'Max140Text',
        },
        # Original Creditor Information
        'original_creditor_name': {
            'business_name': 'Original Creditor Name',
            'business_description': 'Per ISO 20022: Name of the creditor from the original payment.',
            'iso_element_name': 'Name',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/Cdtr/Nm',
            'iso_data_type': 'Max140Text',
        },
        'original_creditor_party_id': {
            'business_name': 'Original Creditor Party ID',
            'business_description': 'Reference to CDM party record for the original creditor.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_creditor_address_country': {
            'business_name': 'Original Creditor Country',
            'business_description': 'Per ISO 20022: Country of the original creditor.',
            'iso_element_name': 'Country',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/Cdtr/PstlAdr/Ctry',
            'iso_data_type': 'CountryCode',
        },
        'original_creditor_account_id': {
            'business_name': 'Original Creditor Account ID',
            'business_description': 'Reference to CDM account record for the original creditor account.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_creditor_account_iban': {
            'business_name': 'Original Creditor Account IBAN',
            'business_description': 'Per ISO 20022: IBAN of the original creditor account.',
            'iso_element_name': 'IBAN',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAcct/Id/IBAN',
            'iso_data_type': 'IBAN2007Identifier',
        },
        'original_creditor_account_other': {
            'business_name': 'Original Creditor Account Other',
            'business_description': 'Per ISO 20022: Non-IBAN account identification of the original creditor.',
            'iso_element_name': 'Identification',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAcct/Id/Othr/Id',
            'iso_data_type': 'Max34Text',
        },
        'original_creditor_agent_bic': {
            'business_name': 'Original Creditor Agent BIC',
            'business_description': 'Per ISO 20022: BIC of the original creditor agent.',
            'iso_element_name': 'BICFI',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/BICFI',
            'iso_data_type': 'BICFIDec2014Identifier',
        },
        'original_creditor_agent_clearing_id': {
            'business_name': 'Original Creditor Agent Clearing ID',
            'business_description': 'Per ISO 20022: Clearing ID of the original creditor agent.',
            'iso_element_name': 'MemberId',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/ClrSysMmbId/MmbId',
            'iso_data_type': 'Max35Text',
        },
        'original_creditor_agent_fi_id': {
            'business_name': 'Original Creditor Agent FI ID',
            'business_description': 'Reference to CDM financial institution record for the original creditor agent.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'original_creditor_agent_name': {
            'business_name': 'Original Creditor Agent Name',
            'business_description': 'Per ISO 20022: Name of the original creditor agent.',
            'iso_element_name': 'Name',
            'iso_element_path': 'Document/PmtRtr/TxInf/OrgnlTxRef/CdtrAgt/FinInstnId/Nm',
            'iso_data_type': 'Max140Text',
        },
        # Return Party Information
        'return_id': {
            'business_name': 'Return ID',
            'business_description': 'Unique identifier for this return transaction in the CDM.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'return_identification': {
            'business_name': 'Return Identification',
            'business_description': 'Per ISO 20022: Unique identification of the return transaction.',
            'iso_element_name': 'RtrId',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrId',
            'iso_data_type': 'Max35Text',
        },
        'return_settlement_date': {
            'business_name': 'Return Settlement Date',
            'business_description': 'Per ISO 20022: Settlement date of the return payment.',
            'iso_element_name': 'RtrdIntrBkSttlmDt',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrdIntrBkSttlmDt',
            'iso_data_type': 'ISODate',
        },
        'returned_settlement_amount': {
            'business_name': 'Returned Settlement Amount',
            'business_description': 'Per ISO 20022: Amount being returned in the settlement.',
            'iso_element_name': 'RtrdIntrBkSttlmAmt',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrdIntrBkSttlmAmt',
            'iso_data_type': 'ActiveCurrencyAndAmount',
        },
        'returned_settlement_currency': {
            'business_name': 'Returned Settlement Currency',
            'business_description': 'Per ISO 20022: Currency of the returned settlement amount.',
            'iso_element_name': 'Currency',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrdIntrBkSttlmAmt/@Ccy',
            'iso_data_type': 'ActiveCurrencyCode',
        },
        'return_originator_bic': {
            'business_name': 'Return Originator BIC',
            'business_description': 'Per ISO 20022: BIC of the party that initiated the return.',
            'iso_element_name': 'BICFI',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrRsnInf/Orgtr/FinInstnId/BICFI',
            'iso_data_type': 'BICFIDec2014Identifier',
        },
        'return_originator_id': {
            'business_name': 'Return Originator ID',
            'business_description': 'Per ISO 20022: Identification of the party that initiated the return.',
            'iso_element_name': 'Identification',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrRsnInf/Orgtr/Id',
            'iso_data_type': 'Party40Choice',
        },
        'return_originator_name': {
            'business_name': 'Return Originator Name',
            'business_description': 'Per ISO 20022: Name of the party that initiated the return.',
            'iso_element_name': 'Name',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrRsnInf/Orgtr/Nm',
            'iso_data_type': 'Max140Text',
        },
        'return_reason_info': {
            'business_name': 'Return Reason Information',
            'business_description': 'Per ISO 20022: Complete return reason information block as JSON.',
            'iso_element_name': 'ReturnReasonInformation',
            'iso_element_path': 'Document/PmtRtr/TxInf/RtrRsnInf',
            'iso_data_type': 'PaymentReturnReason6',
        },
        'return_debtor_party_id': {
            'business_name': 'Return Debtor Party ID',
            'business_description': 'Reference to CDM party record for the debtor in the return.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'return_debtor_account_id': {
            'business_name': 'Return Debtor Account ID',
            'business_description': 'Reference to CDM account record for the debtor account in the return.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'return_debtor_agent_fi_id': {
            'business_name': 'Return Debtor Agent FI ID',
            'business_description': 'Reference to CDM financial institution record for the return debtor agent.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'return_creditor_party_id': {
            'business_name': 'Return Creditor Party ID',
            'business_description': 'Reference to CDM party record for the creditor in the return.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'return_creditor_account_id': {
            'business_name': 'Return Creditor Account ID',
            'business_description': 'Reference to CDM account record for the creditor account in the return.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'return_creditor_agent_fi_id': {
            'business_name': 'Return Creditor Agent FI ID',
            'business_description': 'Reference to CDM financial institution record for the return creditor agent.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
        'source_stg_id': {
            'business_name': 'Source Staging ID',
            'business_description': 'Reference to the Silver layer staging record.',
            'iso_element_name': None,
            'iso_element_path': None,
            'iso_data_type': None,
        },
    },
}

# pacs.003 - FI Direct Debit
CDM_PACS_FI_DIRECT_DEBIT = {
    'cdm_pacs_fi_direct_debit': {
        **{k: v for k, v in _COMMON_PACS_FIELDS.items()},
        'mandate_id': {
            'business_name': 'Mandate Identification',
            'business_description': 'Per ISO 20022: Unique reference assigned by creditor to unambiguously identify the mandate.',
            'iso_element_name': 'MandateIdentification',
            'iso_element_path': 'DrctDbtTxInf/DrctDbtTx/MndtRltdInf/MndtId',
            'iso_data_type': 'Max35Text',
        },
        'mandate_date_of_signature': {
            'business_name': 'Mandate Date of Signature',
            'business_description': 'Per ISO 20022: Date on which the mandate was signed.',
            'iso_element_name': 'DateOfSignature',
            'iso_element_path': 'DrctDbtTxInf/DrctDbtTx/MndtRltdInf/DtOfSgntr',
            'iso_data_type': 'ISODate',
        },
        'creditor_scheme_id': {
            'business_name': 'Creditor Scheme Identification',
            'business_description': 'Per ISO 20022: Unique scheme identification of the creditor.',
            'iso_element_name': 'Identification',
            'iso_element_path': 'DrctDbtTxInf/DrctDbtTx/CdtrSchmeId/Id/PrvtId/Othr/Id',
            'iso_data_type': 'Max35Text',
        },
        'sequence_type': {
            'business_name': 'Sequence Type',
            'business_description': 'Per ISO 20022: Identifies the direct debit sequence. FRST, RCUR, FNAL, OOFF.',
            'iso_element_name': 'SequenceType',
            'iso_element_path': 'DrctDbtTxInf/PmtTpInf/SeqTp',
            'iso_data_type': 'SequenceType3Code',
        },
    },
}

# Combine all pacs definitions
CDM_ISO_PACS = {}
CDM_ISO_PACS.update(CDM_PACS_FI_CUSTOMER_CREDIT_TRANSFER)
CDM_ISO_PACS.update(CDM_PACS_FI_CREDIT_TRANSFER)
CDM_ISO_PACS.update(CDM_PACS_FI_PAYMENT_STATUS_REPORT)
CDM_ISO_PACS.update(CDM_PACS_PAYMENT_RETURN)
CDM_ISO_PACS.update(CDM_PACS_FI_DIRECT_DEBIT)
