"""
CDM Catalog Definitions - ISO 20022 pain (Payment Initiation) Tables
Includes pain.001 (Customer Credit Transfer Initiation), pain.002 (Customer Payment Status Report),
pain.008 (Customer Direct Debit Initiation)
"""

# Common payment initiation fields
_COMMON_PAIN_FIELDS = {
    'instruction_id': {
        'business_name': 'Instruction ID',
        'business_description': 'Unique identifier for this payment instruction in the CDM.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'message_id': {
        'business_name': 'Message Identification',
        'business_description': 'Per ISO 20022: Point-to-point reference assigned by the instructing party to identify the message.',
        'iso_element_name': 'MessageIdentification',
        'iso_element_path': 'GrpHdr/MsgId',
        'iso_data_type': 'Max35Text',
    },
    'creation_datetime': {
        'business_name': 'Creation Date Time',
        'business_description': 'Per ISO 20022: Date and time at which the message was created.',
        'iso_element_name': 'CreationDateTime',
        'iso_element_path': 'GrpHdr/CreDtTm',
        'iso_data_type': 'ISODateTime',
    },
    'number_of_transactions': {
        'business_name': 'Number of Transactions',
        'business_description': 'Per ISO 20022: Number of individual transactions contained in the message.',
        'iso_element_name': 'NumberOfTransactions',
        'iso_element_path': 'GrpHdr/NbOfTxs',
        'iso_data_type': 'Max15NumericText',
    },
    'control_sum': {
        'business_name': 'Control Sum',
        'business_description': 'Per ISO 20022: Total of all individual amounts included in the message for validation.',
        'iso_element_name': 'ControlSum',
        'iso_element_path': 'GrpHdr/CtrlSum',
        'iso_data_type': 'DecimalNumber',
    },
    # Initiating Party
    'initiating_party_name': {
        'business_name': 'Initiating Party Name',
        'business_description': 'Per ISO 20022: Name of the party that initiates the payment.',
        'iso_element_name': 'Name',
        'iso_element_path': 'GrpHdr/InitgPty/Nm',
        'iso_data_type': 'Max140Text',
    },
    'initiating_party_id': {
        'business_name': 'Initiating Party ID',
        'business_description': 'Reference to the CDM party record for the initiating party.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'initiating_party_org_id': {
        'business_name': 'Initiating Party Organisation ID',
        'business_description': 'Per ISO 20022: Unique identification of the initiating party organisation.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'GrpHdr/InitgPty/Id/OrgId/Othr/Id',
        'iso_data_type': 'Max35Text',
    },
    'initiating_party_country': {
        'business_name': 'Initiating Party Country',
        'business_description': 'Per ISO 20022: Country of the initiating party.',
        'iso_element_name': 'Country',
        'iso_element_path': 'GrpHdr/InitgPty/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    # Payment Information
    'payment_info_id': {
        'business_name': 'Payment Information Identification',
        'business_description': 'Per ISO 20022: Unique identification assigned by the initiating party to identify the payment information block.',
        'iso_element_name': 'PaymentInformationIdentification',
        'iso_element_path': 'PmtInf/PmtInfId',
        'iso_data_type': 'Max35Text',
    },
    'payment_method': {
        'business_name': 'Payment Method',
        'business_description': 'Per ISO 20022: Specifies the means of payment. TRF=Credit Transfer, CHK=Cheque, TRA=Transfer Advice.',
        'iso_element_name': 'PaymentMethod',
        'iso_element_path': 'PmtInf/PmtMtd',
        'iso_data_type': 'PaymentMethod3Code',
    },
    'batch_booking': {
        'business_name': 'Batch Booking',
        'business_description': 'Per ISO 20022: Indicates if batch entries should be grouped in a single debit/credit entry.',
        'iso_element_name': 'BatchBooking',
        'iso_element_path': 'PmtInf/BtchBookg',
        'iso_data_type': 'BatchBookingIndicator',
    },
    'requested_execution_date': {
        'business_name': 'Requested Execution Date',
        'business_description': 'Per ISO 20022: Date when the initiating party requests the payment to be executed.',
        'iso_element_name': 'RequestedExecutionDate',
        'iso_element_path': 'PmtInf/ReqdExctnDt',
        'iso_data_type': 'ISODate',
    },
    'requested_collection_date': {
        'business_name': 'Requested Collection Date',
        'business_description': 'Per ISO 20022: Date when the creditor requests the amount to be collected from the debtor (direct debit).',
        'iso_element_name': 'RequestedCollectionDate',
        'iso_element_path': 'PmtInf/ReqdColltnDt',
        'iso_data_type': 'ISODate',
    },
    # Debtor fields
    'debtor_name': {
        'business_name': 'Debtor Name',
        'business_description': 'Per ISO 20022: Name of the party that owes an amount of money.',
        'iso_element_name': 'Name',
        'iso_element_path': 'PmtInf/Dbtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'debtor_party_id': {
        'business_name': 'Debtor Party ID',
        'business_description': 'Reference to the CDM party record for the debtor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'debtor_address_street': {
        'business_name': 'Debtor Street Name',
        'business_description': 'Per ISO 20022: Name of the street or thoroughfare.',
        'iso_element_name': 'StreetName',
        'iso_element_path': 'PmtInf/Dbtr/PstlAdr/StrtNm',
        'iso_data_type': 'Max70Text',
    },
    'debtor_address_building': {
        'business_name': 'Debtor Building Number',
        'business_description': 'Per ISO 20022: Number that identifies the position of the building.',
        'iso_element_name': 'BuildingNumber',
        'iso_element_path': 'PmtInf/Dbtr/PstlAdr/BldgNb',
        'iso_data_type': 'Max16Text',
    },
    'debtor_address_postal_code': {
        'business_name': 'Debtor Postal Code',
        'business_description': 'Per ISO 20022: Identifier for postal delivery.',
        'iso_element_name': 'PostCode',
        'iso_element_path': 'PmtInf/Dbtr/PstlAdr/PstCd',
        'iso_data_type': 'Max16Text',
    },
    'debtor_address_town': {
        'business_name': 'Debtor Town Name',
        'business_description': 'Per ISO 20022: Name of the town, city, or municipality.',
        'iso_element_name': 'TownName',
        'iso_element_path': 'PmtInf/Dbtr/PstlAdr/TwnNm',
        'iso_data_type': 'Max35Text',
    },
    'debtor_address_country': {
        'business_name': 'Debtor Country',
        'business_description': 'Per ISO 20022: Nation with its own government (ISO 3166-1 alpha-2).',
        'iso_element_name': 'Country',
        'iso_element_path': 'PmtInf/Dbtr/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'debtor_id_org_bic': {
        'business_name': 'Debtor Organisation BIC',
        'business_description': 'Per ISO 20022: Business Identifier Code of the debtor organisation.',
        'iso_element_name': 'AnyBIC',
        'iso_element_path': 'PmtInf/Dbtr/Id/OrgId/AnyBIC',
        'iso_data_type': 'AnyBICDec2014Identifier',
    },
    'debtor_id_org_lei': {
        'business_name': 'Debtor Organisation LEI',
        'business_description': 'Per ISO 20022: Legal Entity Identifier of the debtor organisation.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'PmtInf/Dbtr/Id/OrgId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    'debtor_id_org_other': {
        'business_name': 'Debtor Organisation Other ID',
        'business_description': 'Per ISO 20022: Other identification of the debtor organisation.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'PmtInf/Dbtr/Id/OrgId/Othr/Id',
        'iso_data_type': 'Max35Text',
    },
    # Debtor Account
    'debtor_account_iban': {
        'business_name': 'Debtor Account IBAN',
        'business_description': 'Per ISO 20022: International Bank Account Number of the debtor.',
        'iso_element_name': 'IBAN',
        'iso_element_path': 'PmtInf/DbtrAcct/Id/IBAN',
        'iso_data_type': 'IBAN2007Identifier',
    },
    'debtor_account_other': {
        'business_name': 'Debtor Account Other ID',
        'business_description': 'Per ISO 20022: Other identification of the debtor account (non-IBAN).',
        'iso_element_name': 'Identification',
        'iso_element_path': 'PmtInf/DbtrAcct/Id/Othr/Id',
        'iso_data_type': 'Max34Text',
    },
    'debtor_account_type': {
        'business_name': 'Debtor Account Type',
        'business_description': 'Per ISO 20022: Type of account. CACC=Current, SVGS=Savings.',
        'iso_element_name': 'Code',
        'iso_element_path': 'PmtInf/DbtrAcct/Tp/Cd',
        'iso_data_type': 'ExternalCashAccountType1Code',
    },
    'debtor_account_currency': {
        'business_name': 'Debtor Account Currency',
        'business_description': 'Per ISO 20022: Currency of the debtor account.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'PmtInf/DbtrAcct/Ccy',
        'iso_data_type': 'ActiveOrHistoricCurrencyCode',
    },
    # Debtor Agent
    'debtor_agent_bic': {
        'business_name': 'Debtor Agent BIC',
        'business_description': 'Per ISO 20022: Business Identifier Code of the debtor agent (debtor bank).',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'PmtInf/DbtrAgt/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'debtor_agent_fi_id': {
        'business_name': 'Debtor Agent Financial Institution ID',
        'business_description': 'Reference to the CDM financial institution record for the debtor agent.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'debtor_agent_clearing_id': {
        'business_name': 'Debtor Agent Clearing ID',
        'business_description': 'Per ISO 20022: Clearing system member ID of the debtor agent.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'PmtInf/DbtrAgt/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'debtor_agent_name': {
        'business_name': 'Debtor Agent Name',
        'business_description': 'Per ISO 20022: Name of the debtor agent financial institution.',
        'iso_element_name': 'Name',
        'iso_element_path': 'PmtInf/DbtrAgt/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'debtor_agent_country': {
        'business_name': 'Debtor Agent Country',
        'business_description': 'Per ISO 20022: Country of the debtor agent.',
        'iso_element_name': 'Country',
        'iso_element_path': 'PmtInf/DbtrAgt/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    # Transaction fields
    'end_to_end_id': {
        'business_name': 'End to End Identification',
        'business_description': 'Per ISO 20022: Unique identification assigned by the initiating party to unambiguously identify the transaction.',
        'iso_element_name': 'EndToEndIdentification',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/PmtId/EndToEndId',
        'iso_data_type': 'Max35Text',
    },
    'instruction_identification': {
        'business_name': 'Instruction Identification',
        'business_description': 'Per ISO 20022: Unique identification assigned by the instructing party.',
        'iso_element_name': 'InstructionIdentification',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/PmtId/InstrId',
        'iso_data_type': 'Max35Text',
    },
    'uetr': {
        'business_name': 'UETR',
        'business_description': 'Per ISO 20022: Unique End-to-end Transaction Reference (UUID).',
        'iso_element_name': 'UETR',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/PmtId/UETR',
        'iso_data_type': 'UUIDv4Identifier',
    },
    # Amounts
    'instructed_amount': {
        'business_name': 'Instructed Amount',
        'business_description': 'Per ISO 20022: Amount of money to be transferred.',
        'iso_element_name': 'InstructedAmount',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Amt/InstdAmt',
        'iso_data_type': 'ActiveOrHistoricCurrencyAndAmount',
    },
    'instructed_currency': {
        'business_name': 'Instructed Currency',
        'business_description': 'Per ISO 20022: Currency of the instructed amount.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Amt/InstdAmt/@Ccy',
        'iso_data_type': 'ActiveOrHistoricCurrencyCode',
    },
    'equivalent_amount': {
        'business_name': 'Equivalent Amount',
        'business_description': 'Per ISO 20022: Amount of money to be transferred in a different currency.',
        'iso_element_name': 'EquivalentAmount',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Amt/EqvtAmt',
        'iso_data_type': 'EquivalentAmount2',
    },
    # Service Level
    'service_level_code': {
        'business_name': 'Service Level Code',
        'business_description': 'Per ISO 20022: Agreement under which the transaction should be processed.',
        'iso_element_name': 'Code',
        'iso_element_path': 'PmtInf/PmtTpInf/SvcLvl/Cd',
        'iso_data_type': 'ExternalServiceLevel1Code',
    },
    'service_level_proprietary': {
        'business_name': 'Service Level Proprietary',
        'business_description': 'Per ISO 20022: Proprietary service level.',
        'iso_element_name': 'Proprietary',
        'iso_element_path': 'PmtInf/PmtTpInf/SvcLvl/Prtry',
        'iso_data_type': 'Max35Text',
    },
    'local_instrument_code': {
        'business_name': 'Local Instrument Code',
        'business_description': 'Per ISO 20022: Local instrument for the payment.',
        'iso_element_name': 'Code',
        'iso_element_path': 'PmtInf/PmtTpInf/LclInstrm/Cd',
        'iso_data_type': 'ExternalLocalInstrument1Code',
    },
    'category_purpose_code': {
        'business_name': 'Category Purpose Code',
        'business_description': 'Per ISO 20022: High-level purpose of the instruction.',
        'iso_element_name': 'Code',
        'iso_element_path': 'PmtInf/PmtTpInf/CtgyPurp/Cd',
        'iso_data_type': 'ExternalCategoryPurpose1Code',
    },
    'instruction_priority': {
        'business_name': 'Instruction Priority',
        'business_description': 'Per ISO 20022: Urgency of the instruction. HIGH or NORM.',
        'iso_element_name': 'InstructionPriority',
        'iso_element_path': 'PmtInf/PmtTpInf/InstrPrty',
        'iso_data_type': 'Priority2Code',
    },
    # Creditor fields
    'creditor_name': {
        'business_name': 'Creditor Name',
        'business_description': 'Per ISO 20022: Name of the party to which money is due.',
        'iso_element_name': 'Name',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Cdtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'creditor_party_id': {
        'business_name': 'Creditor Party ID',
        'business_description': 'Reference to the CDM party record for the creditor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'creditor_address_street': {
        'business_name': 'Creditor Street Name',
        'business_description': 'Per ISO 20022: Street name of the creditor address.',
        'iso_element_name': 'StreetName',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Cdtr/PstlAdr/StrtNm',
        'iso_data_type': 'Max70Text',
    },
    'creditor_address_town': {
        'business_name': 'Creditor Town Name',
        'business_description': 'Per ISO 20022: Town name of the creditor address.',
        'iso_element_name': 'TownName',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Cdtr/PstlAdr/TwnNm',
        'iso_data_type': 'Max35Text',
    },
    'creditor_address_postal_code': {
        'business_name': 'Creditor Postal Code',
        'business_description': 'Per ISO 20022: Postal code of the creditor address.',
        'iso_element_name': 'PostCode',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Cdtr/PstlAdr/PstCd',
        'iso_data_type': 'Max16Text',
    },
    'creditor_address_country': {
        'business_name': 'Creditor Country',
        'business_description': 'Per ISO 20022: Country of the creditor.',
        'iso_element_name': 'Country',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Cdtr/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    'creditor_id_org_bic': {
        'business_name': 'Creditor Organisation BIC',
        'business_description': 'Per ISO 20022: BIC of the creditor organisation.',
        'iso_element_name': 'AnyBIC',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Cdtr/Id/OrgId/AnyBIC',
        'iso_data_type': 'AnyBICDec2014Identifier',
    },
    'creditor_id_org_lei': {
        'business_name': 'Creditor Organisation LEI',
        'business_description': 'Per ISO 20022: LEI of the creditor organisation.',
        'iso_element_name': 'LEI',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Cdtr/Id/OrgId/LEI',
        'iso_data_type': 'LEIIdentifier',
    },
    # Creditor Account
    'creditor_account_iban': {
        'business_name': 'Creditor Account IBAN',
        'business_description': 'Per ISO 20022: IBAN of the creditor account.',
        'iso_element_name': 'IBAN',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAcct/Id/IBAN',
        'iso_data_type': 'IBAN2007Identifier',
    },
    'creditor_account_other': {
        'business_name': 'Creditor Account Other ID',
        'business_description': 'Per ISO 20022: Other identification of the creditor account.',
        'iso_element_name': 'Identification',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAcct/Id/Othr/Id',
        'iso_data_type': 'Max34Text',
    },
    'creditor_account_type': {
        'business_name': 'Creditor Account Type',
        'business_description': 'Per ISO 20022: Type of creditor account.',
        'iso_element_name': 'Code',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAcct/Tp/Cd',
        'iso_data_type': 'ExternalCashAccountType1Code',
    },
    'creditor_account_currency': {
        'business_name': 'Creditor Account Currency',
        'business_description': 'Per ISO 20022: Currency of the creditor account.',
        'iso_element_name': 'Currency',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAcct/Ccy',
        'iso_data_type': 'ActiveOrHistoricCurrencyCode',
    },
    # Creditor Agent
    'creditor_agent_bic': {
        'business_name': 'Creditor Agent BIC',
        'business_description': 'Per ISO 20022: BIC of the creditor agent.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAgt/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'creditor_agent_fi_id': {
        'business_name': 'Creditor Agent Financial Institution ID',
        'business_description': 'Reference to the CDM financial institution record.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'creditor_agent_clearing_id': {
        'business_name': 'Creditor Agent Clearing ID',
        'business_description': 'Per ISO 20022: Clearing system member ID of the creditor agent.',
        'iso_element_name': 'MemberId',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAgt/FinInstnId/ClrSysMmbId/MmbId',
        'iso_data_type': 'Max35Text',
    },
    'creditor_agent_name': {
        'business_name': 'Creditor Agent Name',
        'business_description': 'Per ISO 20022: Name of the creditor agent.',
        'iso_element_name': 'Name',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAgt/FinInstnId/Nm',
        'iso_data_type': 'Max140Text',
    },
    'creditor_agent_country': {
        'business_name': 'Creditor Agent Country',
        'business_description': 'Per ISO 20022: Country of the creditor agent.',
        'iso_element_name': 'Country',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/CdtrAgt/FinInstnId/PstlAdr/Ctry',
        'iso_data_type': 'CountryCode',
    },
    # Intermediary Agent
    'intermediary_agent1_bic': {
        'business_name': 'Intermediary Agent 1 BIC',
        'business_description': 'Per ISO 20022: BIC of the first intermediary agent.',
        'iso_element_name': 'BICFI',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/IntrmyAgt1/FinInstnId/BICFI',
        'iso_data_type': 'BICFIDec2014Identifier',
    },
    'intermediary_agent1_fi_id': {
        'business_name': 'Intermediary Agent 1 FI ID',
        'business_description': 'Reference to CDM FI record for intermediary agent 1.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    # Ultimate Debtor/Creditor
    'ultimate_debtor_name': {
        'business_name': 'Ultimate Debtor Name',
        'business_description': 'Per ISO 20022: Ultimate party that owes the money.',
        'iso_element_name': 'Name',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/UltmtDbtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'ultimate_debtor_party_id': {
        'business_name': 'Ultimate Debtor Party ID',
        'business_description': 'Reference to CDM party record for the ultimate debtor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'ultimate_creditor_name': {
        'business_name': 'Ultimate Creditor Name',
        'business_description': 'Per ISO 20022: Ultimate party to which money is due.',
        'iso_element_name': 'Name',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/UltmtCdtr/Nm',
        'iso_data_type': 'Max140Text',
    },
    'ultimate_creditor_party_id': {
        'business_name': 'Ultimate Creditor Party ID',
        'business_description': 'Reference to CDM party record for the ultimate creditor.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    # Purpose
    'purpose_code': {
        'business_name': 'Purpose Code',
        'business_description': 'Per ISO 20022: Underlying reason for the payment.',
        'iso_element_name': 'Code',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Purp/Cd',
        'iso_data_type': 'ExternalPurpose1Code',
    },
    'purpose_proprietary': {
        'business_name': 'Purpose Proprietary',
        'business_description': 'Per ISO 20022: Proprietary purpose code.',
        'iso_element_name': 'Proprietary',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/Purp/Prtry',
        'iso_data_type': 'Max35Text',
    },
    # Remittance Information
    'remittance_unstructured': {
        'business_name': 'Remittance Information Unstructured',
        'business_description': 'Per ISO 20022: Information to enable matching with items to settle.',
        'iso_element_name': 'Unstructured',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/RmtInf/Ustrd',
        'iso_data_type': 'Max140Text',
    },
    'remittance_structured': {
        'business_name': 'Remittance Information Structured',
        'business_description': 'Per ISO 20022: Structured remittance information.',
        'iso_element_name': 'Structured',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/RmtInf/Strd',
        'iso_data_type': 'StructuredRemittanceInformation16',
    },
    # Regulatory Reporting
    'regulatory_reporting': {
        'business_name': 'Regulatory Reporting',
        'business_description': 'Per ISO 20022: Information for regulatory requirements.',
        'iso_element_name': 'RegulatoryReporting',
        'iso_element_path': 'PmtInf/CdtTrfTxInf/RgltryRptg',
        'iso_data_type': 'RegulatoryReporting3',
    },
    # Charge Bearer
    'charge_bearer': {
        'business_name': 'Charge Bearer',
        'business_description': 'Per ISO 20022: Specifies which party bears charges. DEBT, CRED, SHAR, SLEV.',
        'iso_element_name': 'ChargeBearer',
        'iso_element_path': 'PmtInf/ChrgBr',
        'iso_data_type': 'ChargeBearerType1Code',
    },
    # Charges Account
    'charges_account_iban': {
        'business_name': 'Charges Account IBAN',
        'business_description': 'Per ISO 20022: IBAN of the account to be charged for charges.',
        'iso_element_name': 'IBAN',
        'iso_element_path': 'PmtInf/ChrgsAcct/Id/IBAN',
        'iso_data_type': 'IBAN2007Identifier',
    },
    # Source/Lineage fields
    'source_format': {
        'business_name': 'Source Format',
        'business_description': 'Original message format from which this record was derived.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'source_stg_table': {
        'business_name': 'Source Staging Table',
        'business_description': 'Silver layer staging table from which this record was derived.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'stg_id': {
        'business_name': 'Staging ID',
        'business_description': 'Reference to the Silver layer staging record.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'raw_id': {
        'business_name': 'Raw ID',
        'business_description': 'Reference to the Bronze layer raw record.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'batch_id': {
        'business_name': 'Batch ID',
        'business_description': 'Identifier of the processing batch.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
    'processing_status': {
        'business_name': 'Processing Status',
        'business_description': 'Current processing status in the CDM pipeline.',
        'iso_element_name': None,
        'iso_element_path': None,
        'iso_data_type': None,
    },
}

# pain.001 - Customer Credit Transfer Initiation
CDM_PAIN_CUSTOMER_CREDIT_TRANSFER_INITIATION = {
    'cdm_pain_customer_credit_transfer_initiation': _COMMON_PAIN_FIELDS,
}

# pain.002 - Customer Payment Status Report
CDM_PAIN_CUSTOMER_PAYMENT_STATUS_REPORT = {
    'cdm_pain_customer_payment_status_report': {
        **{k: v for k, v in _COMMON_PAIN_FIELDS.items() if k in [
            'instruction_id', 'message_id', 'creation_datetime', 'end_to_end_id',
            'instruction_identification', 'uetr', 'stg_id', 'raw_id', 'batch_id',
            'processing_status', 'source_format', 'source_stg_table'
        ]},
        'original_message_id': {
            'business_name': 'Original Message Identification',
            'business_description': 'Per ISO 20022: Reference to the original payment initiation message.',
            'iso_element_name': 'OrgnlMsgId',
            'iso_element_path': 'OrgnlGrpInfAndSts/OrgnlMsgId',
            'iso_data_type': 'Max35Text',
        },
        'original_message_name_id': {
            'business_name': 'Original Message Name',
            'business_description': 'Per ISO 20022: Name of the original message (e.g., pain.001).',
            'iso_element_name': 'OrgnlMsgNmId',
            'iso_element_path': 'OrgnlGrpInfAndSts/OrgnlMsgNmId',
            'iso_data_type': 'Max35Text',
        },
        'original_creation_datetime': {
            'business_name': 'Original Creation Date Time',
            'business_description': 'Per ISO 20022: Creation date of the original message.',
            'iso_element_name': 'OrgnlCreDtTm',
            'iso_element_path': 'OrgnlGrpInfAndSts/OrgnlCreDtTm',
            'iso_data_type': 'ISODateTime',
        },
        'original_number_of_transactions': {
            'business_name': 'Original Number of Transactions',
            'business_description': 'Per ISO 20022: Number of transactions in original message.',
            'iso_element_name': 'OrgnlNbOfTxs',
            'iso_element_path': 'OrgnlGrpInfAndSts/OrgnlNbOfTxs',
            'iso_data_type': 'Max15NumericText',
        },
        'original_control_sum': {
            'business_name': 'Original Control Sum',
            'business_description': 'Per ISO 20022: Control sum of the original message.',
            'iso_element_name': 'OrgnlCtrlSum',
            'iso_element_path': 'OrgnlGrpInfAndSts/OrgnlCtrlSum',
            'iso_data_type': 'DecimalNumber',
        },
        'group_status': {
            'business_name': 'Group Status',
            'business_description': 'Per ISO 20022: Status of the group. ACTC, ACCP, ACSP, ACSC, RJCT.',
            'iso_element_name': 'GroupStatus',
            'iso_element_path': 'OrgnlGrpInfAndSts/GrpSts',
            'iso_data_type': 'ExternalPaymentGroupStatus1Code',
        },
        'transaction_status': {
            'business_name': 'Transaction Status',
            'business_description': 'Per ISO 20022: Status of an individual transaction.',
            'iso_element_name': 'TransactionStatus',
            'iso_element_path': 'OrgnlPmtInfAndSts/TxInfAndSts/TxSts',
            'iso_data_type': 'ExternalPaymentTransactionStatus1Code',
        },
        'status_reason_code': {
            'business_name': 'Status Reason Code',
            'business_description': 'Per ISO 20022: Reason for the status.',
            'iso_element_name': 'Code',
            'iso_element_path': 'OrgnlPmtInfAndSts/TxInfAndSts/StsRsnInf/Rsn/Cd',
            'iso_data_type': 'ExternalStatusReason1Code',
        },
        'status_reason_proprietary': {
            'business_name': 'Status Reason Proprietary',
            'business_description': 'Per ISO 20022: Proprietary status reason.',
            'iso_element_name': 'Proprietary',
            'iso_element_path': 'OrgnlPmtInfAndSts/TxInfAndSts/StsRsnInf/Rsn/Prtry',
            'iso_data_type': 'Max35Text',
        },
        'status_additional_info': {
            'business_name': 'Additional Status Information',
            'business_description': 'Per ISO 20022: Additional information about the status.',
            'iso_element_name': 'AdditionalInformation',
            'iso_element_path': 'OrgnlPmtInfAndSts/TxInfAndSts/StsRsnInf/AddtlInf',
            'iso_data_type': 'Max105Text',
        },
        'acceptance_datetime': {
            'business_name': 'Acceptance Date Time',
            'business_description': 'Per ISO 20022: Date and time at which the status was determined.',
            'iso_element_name': 'AcceptanceDateTime',
            'iso_element_path': 'OrgnlPmtInfAndSts/TxInfAndSts/AccptncDtTm',
            'iso_data_type': 'ISODateTime',
        },
    },
}

# pain.008 - Customer Direct Debit Initiation
CDM_PAIN_CUSTOMER_DIRECT_DEBIT_INITIATION = {
    'cdm_pain_customer_direct_debit_initiation': {
        **_COMMON_PAIN_FIELDS,
        'mandate_id': {
            'business_name': 'Mandate Identification',
            'business_description': 'Per ISO 20022: Unique reference assigned by creditor to identify the mandate.',
            'iso_element_name': 'MandateIdentification',
            'iso_element_path': 'PmtInf/DrctDbtTxInf/DrctDbtTx/MndtRltdInf/MndtId',
            'iso_data_type': 'Max35Text',
        },
        'mandate_date_of_signature': {
            'business_name': 'Mandate Date of Signature',
            'business_description': 'Per ISO 20022: Date on which the mandate was signed.',
            'iso_element_name': 'DateOfSignature',
            'iso_element_path': 'PmtInf/DrctDbtTxInf/DrctDbtTx/MndtRltdInf/DtOfSgntr',
            'iso_data_type': 'ISODate',
        },
        'amendment_indicator': {
            'business_name': 'Amendment Indicator',
            'business_description': 'Per ISO 20022: Indicates if the mandate has been amended.',
            'iso_element_name': 'AmendmentIndicator',
            'iso_element_path': 'PmtInf/DrctDbtTxInf/DrctDbtTx/MndtRltdInf/AmdmntInd',
            'iso_data_type': 'TrueFalseIndicator',
        },
        'creditor_scheme_id': {
            'business_name': 'Creditor Scheme Identification',
            'business_description': 'Per ISO 20022: Unique identification of the creditor scheme.',
            'iso_element_name': 'Identification',
            'iso_element_path': 'PmtInf/CdtrSchmeId/Id/PrvtId/Othr/Id',
            'iso_data_type': 'Max35Text',
        },
        'creditor_scheme_name': {
            'business_name': 'Creditor Scheme Name',
            'business_description': 'Per ISO 20022: Name of the creditor scheme.',
            'iso_element_name': 'SchemeName',
            'iso_element_path': 'PmtInf/CdtrSchmeId/Id/PrvtId/Othr/SchmeNm/Prtry',
            'iso_data_type': 'Max35Text',
        },
        'sequence_type': {
            'business_name': 'Sequence Type',
            'business_description': 'Per ISO 20022: Direct debit sequence. FRST, RCUR, FNAL, OOFF.',
            'iso_element_name': 'SequenceType',
            'iso_element_path': 'PmtInf/PmtTpInf/SeqTp',
            'iso_data_type': 'SequenceType3Code',
        },
        'pre_notification_id': {
            'business_name': 'Pre-Notification Identification',
            'business_description': 'Per ISO 20022: Reference of the direct debit pre-notification.',
            'iso_element_name': 'PreNotificationIdentification',
            'iso_element_path': 'PmtInf/DrctDbtTxInf/DrctDbtTx/PreNtfctnId',
            'iso_data_type': 'Max35Text',
        },
        'pre_notification_date': {
            'business_name': 'Pre-Notification Date',
            'business_description': 'Per ISO 20022: Date of the pre-notification.',
            'iso_element_name': 'PreNotificationDate',
            'iso_element_path': 'PmtInf/DrctDbtTxInf/DrctDbtTx/PreNtfctnDt',
            'iso_data_type': 'ISODate',
        },
    },
}

# Combine all pain definitions
CDM_ISO_PAIN = {}
CDM_ISO_PAIN.update(CDM_PAIN_CUSTOMER_CREDIT_TRANSFER_INITIATION)
CDM_ISO_PAIN.update(CDM_PAIN_CUSTOMER_PAYMENT_STATUS_REPORT)
CDM_ISO_PAIN.update(CDM_PAIN_CUSTOMER_DIRECT_DEBIT_INITIATION)
